### ISSUE TITLE
Getting  ReflectionTypeLoadException when loading a dll from a different directory 

### ISSUE THREAD

**Issue by arthurvaverko** [natemcmaster/DotNetCorePlugins#10]
**Describe the bug**
Code:

```
var loader = PluginLoader.CreateFromAssemblyFile(
                    assemblyFile: @"D:\Sources\MyTaskDlls\Task1.dll",
                    sharedTypes: new[] {typeof(ITaskHandler)});
                var taskHandlersInAssembly = loader.LoadDefaultAssembly().GetTypes().Where(t => typeof(ITaskHandler).IsAssignableFrom(t));
                var taskHandlerType = taskHandlersInAssembly.First();

                var taskHandlerInstance = (ITaskHandler) Activator.CreateInstance(taskHandlerType);
                var response = taskHandlerInstance.HandleTask("blablbalba");
```
loader.LoadDefaultAssembly() throws the following exception:
"System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.\r\n   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)\r\n   at System.Reflection.Assembly.GetTypes()\r\n   at ...

**Comment by arthurvaverko** [comment]
this migth help .. 
https://stackoverflow.com/a/38843565/605129

**Comment by natemcmaster** [comment]
Can you provide a minimal repro and/or more details? Which version of the plugins library are you using? Did this work in earlier versions and regress? Or did it never work?

**Comment by arthurvaverko** [comment]
Don't know about regression because I only started using this lib.

I'll try to create a small console app and upload to a repo in the next
couple of days.

I'm using the latest version...
