### ISSUE TITLE
[Question] Load any DLL? 

### ISSUE THREAD

**Issue by Andale-online** [natemcmaster/DotNetCorePlugins#103]
Can I use any DLL as plugin or only these implementing the getname method?

Samples look that way but readme looks like you need the iplugin interface. What's correct? Maybe update the readme?

**Comment by natemcmaster** [comment]
Good question. Can you take a look at https://github.com/natemcmaster/DotNetCorePlugins/pull/104 and let me know if that answers your question?

The short answer - yes, you can load any DLL. Defining a contract with an interface `IPlugin` is a suggestion, not a requirement.

**Comment by Andale-online** [comment]
Perfect! Thanks a lot!
