### ISSUE TITLE
Importing in VS2019 took 2 hours

### ISSUE THREAD

**Issue by Andale-online** [natemcmaster/DotNetCorePlugins#107]
**Describe the bug**
Tried to load the project into mine. The project files get loaded but are unusable. I made a retarget to netstandard2.0 (our libraries are netstandard based, while the service is netcore3)

**To Reproduce**
Include the .SLN or .csproj in another solution.

**Expected behavior**
Library gets loaded and I can reference it.

**Additional context**
I now have a working version, I'll give you a WIP pr so you can check out how much I had to remove.

What kind of IDE are you using??? Never seen that structure of project

**Comment by jzabroski** [comment]
How many nuget packages do you have in your nuget package cache?  I have seen similar issues with other projects due to huge # of nuget packages.

**Comment by jzabroski** [comment]
Also, if you have a small repro, consider putting it on GitHub and filing it against Visual Studio Engineering via the Report a Problem link in Visual Studio Help menu.  I don't think this project is likely the guilty party.

**Comment by natemcmaster** [comment]
Microsoft Visual Studio Enterprise 2019
Version 16.4.0

Currently my solution loads in < 20 seconds.  I develop in an Azure VM - size Standard D4s v3 (4 vcpus, 16 GiB memory).
