### ISSUE TITLE
Target dotnetcore3.1

### ISSUE THREAD

**Issue by iron9light** [natemcmaster/DotNetCorePlugins#112]
Target dotnetcore 3.1 since it's LTS version.
And it will be better if it supports Nullable Reference.

**Comment by natemcmaster** [comment]
Other than LTS designation, is there a reason to upgrade?

Also, this library supports nullable reference types already :)  https://github.com/natemcmaster/DotNetCorePlugins/blob/e5d74ec3f35c70dc2618f6d38615de356485ccdd/Directory.Build.props#L22

**Comment by iron9light** [comment]
No other reason for me.
I just upgraded all my projects from dotnetcore 3.0 -> 3.1.
I think all dotnetcore 3.0 projects should upgrade to 3.1.
3.0 is more like a beta/RC.

**Comment by natemcmaster** [comment]
Ok, thanks for clarifying. 

I'm planning to leave this library targeting netcoreapp3.0 and netcoreapp2.0 until there is a need for a higher target framework version. (For example, earlier versions of this library only had netcoreapp2.0, but I added 3.0 to support unloadability and hot reload.) It's my opinion that _libraries_ should use the _lowest_ target framework possible. This maximizes the number of end users who can consume this library without forcing them to upgrade to a new version of .NET Core.

If you find a reason, other than the LTS designation, that the upgrade is needed, let me know.

**Comment by iron9light** [comment]
make sence.
