### ISSUE TITLE
How to get a type of a reference assembly from plugin loader?

### ISSUE THREAD

**Issue by cpkuo** [natemcmaster/DotNetCorePlugins#121]
I have a plugin that has a DLL reference that contains a concrete class that is only used in the plugin's Startup class as apart of the DI registration. Once I've retrieved the assembly via LoadDefaultAssembly(), is there a way to retrieve the type of that reference/concrete class? I've tried the following and my type returns null:

- First tried getting the type from the default assembly
`pluginAssembly.GetType("ReferenceAssembly.ConcreteClassName");`

- Then attempted to load the reference assembly in the plugin loader 
`pluginLoader.LoadAssembly(referenceAssemblyName); `
 After forcing the reference assembly to load into the load context, attempted to get the reference type using EnterContextualReflection like:
`                                using (pluginLoader.EnterContextualReflection())
                                {
                                    var myPluginType = Type.GetType("ReferenceAssembly.ConcreteClassName");
                                }`

**Comment by cpkuo** [comment]
Sorry, the EnterContextualReflection() does work, I just left out the assembly name in the string so now it looks like "ReferenceAssembly.ConcreteClassName, ReferenceAssembly".

Btw, your plugin loader is a life saver!

**Comment by natemcmaster** [comment]
Glad you figured it out! Thanks for sharing your findings :)
