### ISSUE TITLE
Exclusions from Shared Types

### ISSUE THREAD

**Issue by cpkuo** [natemcmaster/DotNetCorePlugins#122]
Is there a way to prefer shared types but provide a list of exclusions? My scenario is that my host app is an AspNet application and the plugins are also AspNet applications where I would like to share the necessary types that the host provides for AspNet. However, in the host there might be a reference to a non-framework nuget package that if a plugin also uses, that they use their own version and not the version from the host. One option is I could explicitly define all types in shared AspNet framework but that would rather large and I would present a maintenance challenge.

**Comment by natemcmaster** [comment]
That is what this API is for :)

https://github.com/natemcmaster/DotNetCorePlugins/blob/370d3558e675e195728d02df5c9bf2f59d258a51/src/Plugins/PluginConfig.cs#L41-L44

Usage would look something like
```csharp
PluginLoader.CreateFromAssemblyFile(
    assemblyFile: "./plugins/MyPlugin/MyPlugin1.dll",
    config =>
    {
        config.PreferSharedTypes = true;
        config.PrivateAssemblies.Add(new AssemblyName("MyPrivateAssembly, PublicKeyToken=abcxyz, Culture=neutral"));
    });
```

Disclaimer: any thing a shared type depends on cannot be a private type. This might limit what you can actually accomplish with this API depending on the shape of your dependency tree.
