### ISSUE TITLE
Net Core 3.1 Unload Plugin

### ISSUE THREAD

**Issue by ThorstenWeiss** [natemcmaster/DotNetCorePlugins#126]
**Is your feature request related to a problem? Please describe.**
is the unload feature already published in the latest release? If i use load.Dispose() the plugin is not unloaded from the memory.
All registered controllers or application parts are ready to use. 
Do you have an example for unloading the plugin and all parts?

**Describe the solution you'd like**
The unload function will remove the plugin from memory and remove all application parts.

**Describe alternatives you've considered**
an example for remove all parts by my own.

**Comment by natemcmaster** [comment]
Yes, unloading is implemented. Did you set IsUnloadable to true?

https://github.com/natemcmaster/DotNetCorePlugins/blob/8312d70c90801f6caf3f39b6e1341d26689c5111/src/Plugins/PluginConfig.cs#L78

If you did and it's still not working, I recommend reading https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability if you are having trouble with assemblies that won't unload. An important thing to understand is that unloading is async and will not complete if anything from the context is still in use, either by call stack or strong references. GC cleans up the load context eventually. So, for example, ASP.NET Core MVC can keep references to controllers indefinitely; ASP.NET Core does not support unloading controllers.
