### ISSUE TITLE
[Question] How to load plugins that reference System.Management in .NET Core?

### ISSUE THREAD

**Issue by FramnkRulez** [natemcmaster/DotNetCorePlugins#131]
I've been trying unsuccessfully to get a plugin to work that references System.Management without adding that reference to System.Management directly to the parent project and passing the types I want to use in the shared types collection.  Any attempt to access a type within System.Management without doing this results in this exception being thrown:

"System.Management currently is only supported for Windows desktop applications."

Any advice?

**Comment by natemcmaster** [comment]
Can you share code to reproduce this error?

**Comment by FramnkRulez** [comment]
I've attached a sample project that demonstrates the issue with a plugin referencing System.Management.

[pluginloader.zip](https://github.com/natemcmaster/DotNetCorePlugins/files/4325563/pluginloader.zip)

**Comment by natemcmaster** [comment]
I don't have Windows handy to try this, but from a quick inspection it seems like your problem is `<TargetFramework>netstandard2.0</TargetFramework>`. Typically, it is best to implement plugins by targeting `netcoreapp2.0` or higher. Try changing the target framework of your plugin.

**Comment by FramnkRulez** [comment]
That seemed to work, thank you!
