### ISSUE TITLE
Blazor plugins?

### ISSUE THREAD

**Issue by pauloolileal** [natemcmaster/DotNetCorePlugins#134]
I would like to know if there will be portability to use the plugins with Blazor, in a similar way as it works with MVC.

I really like the library and I want to be able to use it in Blazor applications.

**Comment by godrose** [comment]
@pauloolileal Have you tried it?

**Comment by pauloolileal** [comment]
> @pauloolileal Have you tried it?

If you use Razor Pages with Blazor, it works. But not as a SPA. Besides, my tests were very simple.

**Comment by natemcmaster** [comment]
I'm not planning to do anything special here to support Blazor.

Assuming you mean Blazor server-side rendering, I don't see any reason why you couldn't use this library as-is. 

Blazor in the browser using WASM is definitely out of scope and will almost definitely never work with this library.

**Comment by HybridSolutions** [comment]
Hi great work here! It would be nice to have a sample using Blazor to load a plugin with a razor page with some content.
