### ISSUE TITLE
HotReload MVC

### ISSUE THREAD

**Issue by diegoth-dev** [natemcmaster/DotNetCorePlugins#135]
Is HotReload in MVC possible?

**Comment by natemcmaster** [comment]
No.

**Comment by B-Esmaili** [comment]
Is there any plan to implement it? or is it possible at all?if yes could you give me some clue to get my hands dirty?

**Comment by natemcmaster** [comment]
@B-Esmaili take a look at https://github.com/natemcmaster/DotNetCorePlugins/issues/82 first. Before HotReload is possible, someone needs to figure out if its possible to register MVC controllers and views dynamically. As far as I know, this can only happen during startup, but I haven't looked very hard for a solution.

Assuming #82 can be solved, then the next problem would be how to de-registry views and controllers. If that can be done, then you should be able to combine both elements into an MVC hot-reload feature.
