### ISSUE TITLE
.Net 5.0 preview support

### ISSUE THREAD

**Issue by iq666** [natemcmaster/DotNetCorePlugins#151]
I have issues with using XML in a plugin. I understand that this is a .Net Core issue and will be fixed in .Net Core 5.0.  Is there any chance of a build with .Net 5.0 preview support?

**Comment by natemcmaster** [comment]
What changes are needed here to support .NET 5? Have you tested this library and found any issues on .NET 5?

**Comment by iq666** [comment]
My bad. Issues were mine not in DotNetCorePlugins.
