### ISSUE TITLE
[Question] Defining multiple Contract Type

### ISSUE THREAD

**Issue by aloksharma1** [natemcmaster/DotNetCorePlugins#152]
Hello,
i have been wondering if its possible to use multiple contracts, like this in same assembly:
IPlugin
ISearchPlugin
IMenuPlugin

etc?
the reason for this is i have self build plugin loader similar to yours in mvc5 , now i found yours which is almost identical to how i load things in my application plus i dont need to rewrite my plugin loader again for .net core version 👍.
this is the use case we have for our assemblies, let me know if i can do this by default calls or do i need to customize your source code.
thanks for the great work.

**Comment by natemcmaster** [comment]
Yes, you can define multiple contract types by default.

**Comment by aloksharma1** [comment]
thanks for the reply, can you provide me with correct documentation.
regards

**Comment by KatoStoelen** [comment]
You can find what you are looking for in the [Getting Started section of README.md](https://github.com/natemcmaster/DotNetCorePlugins#getting-started). Look for `sharedTypes`.

You can read more about shared types [here](https://github.com/natemcmaster/DotNetCorePlugins#shared-types) and [here](https://github.com/natemcmaster/DotNetCorePlugins/blob/main/docs/what-are-shared-types.md).

Looking at the internals of `PluginLoader`,

https://github.com/natemcmaster/DotNetCorePlugins/blob/84028845c24a8ca8b6cfda245154dfc7ef32e60b/src/Plugins/PluginLoader.cs#L115-L118

if all your contracts are in the same assembly, it should be sufficient to add one of them to the list of shared types, as the whole assembly will be shared between the host and the plugins.

**Comment by natemcmaster** [comment]
Closing as I believe the question was answered. Thanks @KatoStoelen
