### ISSUE TITLE
SeriLog write nothing from assembly load with plugin framework

### ISSUE THREAD

**Issue by zraffaele** [natemcmaster/DotNetCorePlugins#153]
I'm usign Serilog for logging and in the plugin assembly loaded with dependency-injection like sample, the Log.Logger write nothing in the console or in the file sink.
Note that the plugin is loaded from a worker service and if load directly the class without the plugin framework, the Log.Logger works properly
Thanks in advance.

**Comment by zraffaele** [comment]
Resolve it i'm added a sharedTypes (typeof(ILogger)) in  PluginLoader.CreateFromAssemblyFile

**Comment by VictorioBerra** [comment]
Having same issue, I am unable to inject ILogger into a class that I register with services.AddTransient. Core 3.1
