### ISSUE TITLE
[Question] - would you consider a PR to use IFileProvider (Watch) here?

### ISSUE THREAD

**Issue by dazinator** [natemcmaster/DotNetCorePlugins#154]
For the hot reload, I can see you create a file watcher:

https://github.com/natemcmaster/DotNetCorePlugins/blob/main/src/Plugins/PluginLoader.cs#L222

My first thought was: Would you consider accepting an `IFileProvider` instead from `Microsoft.Extensions.FileProviders.Abstractions` plus perhaps some watch patterns?

So the API could become something like:

```
.EnableHotReload(Environment.ContentRootFileProvider, "/shadowcopy/*.plugin.dll");
```

The reason I was thinking this is because a `PhysicalFileProvider` does use a watcher, but it also has workarounds to fall back to polling etc in which make it more robust in certain environments / situations.

However looking at the hot reload - it looks like it just wants to be signalled when it needs to reload - it doesnt need to know what changed or even that it was a physical file. So I was thinking it might make sense to provide a more general purpose api that takes a change token? https://docs.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?view=aspnetcore-3.1#simple-startup-change-token

```
.EnableHotReload(() => config.GetReloadToken()); // could be anything that returns an IChangeToken such as IFileProvider.Watch or a user constructed one etc,

```

Then helper methods can be written to supply change tokens using a watcher, IFileProvider.Watch, or a user could supply their own, triggered of the back of a database change if they wished (i.e suppose they maintain in the database which plugins should be enabled / disabled, and this impacts which ones are included when loaded on startup).

**Comment by dazinator** [comment]
The reason I suggest that is because a `PhysicalFileProvider` does use a watcher, but it also has workarounds to fall back to polling etc which make it more robust on certain environments..

**Comment by dazinator** [comment]
Another idea, I noticed that all the hot reload is doing is waiting for a change to be signalled to trigger a reload. I wonder if you could supply a more generic form of this that just accepts perhaps a `IChangeToken` and let's the user signal that however they want.

**Comment by natemcmaster** [comment]
Thanks for asking! I probably wouldn't accept a PR to add this new dependency. This library intentionally seeks to minimize the additional dependencies pulled into the app as new dependencies can complicate the way assembly loading occurs. I am actually considering droppin 100% of dependencies in .NET 5 as I think the 'in-box' API is now sufficient for this library.

**Comment by dazinator** [comment]
Ok I see!
If I wanted to trigger a reload off the back of an IChangeToken (Microsoft.Extensions.Primitives) or some other mechanism, I guess as the Reload() method is public, I can just set up whatever mechanism I like to call it whenever I like. So I guess the current FileWatcher based HotReload method that is currently provided is purely for convenience and not mandatory. Based on that, closing this issue.
