### ISSUE TITLE
Consider supporting netcoreapp3.1 with FEATURE_UNLOAD constant.

### ISSUE THREAD

**Issue by B-Esmaili** [natemcmaster/DotNetCorePlugins#156]
In `McMaster.NETCore.Plugins.csproj` you check for netcoreapp3.0  to enable hot-reload feature for netcoreapp3.0 and it seems it is not working with higher framework version (3.1). Could you please consider improving this condition to support netcoreapp3.0 and greater versions?

**Comment by natemcmaster** [comment]
TargetFramework represents a *minimum* version. No changes are required to the way this project compiles to make unloading feature work on 3.1.

**Comment by Simonl9l** [comment]
@natemcmaster - it would be great to revisit this and perhaps re-open? -  it seems this` DefineConstants` is not work under dotnet 6 where the framework is 
```XML
<TargetFramework>net6.0</TargetFramework>
```

if I go to the source (decompiled) for I get noting that `FEATURE_UNLOAD` is not defied:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/66816457/144785895-56066f1f-7e18-4047-9b5a-f52eb65dc330.png">

I assume the same fix is required for `FEATURE_NATIVE_RESOLVER`?

 per [this](https://docs.microsoft.com/en-us/dotnet/standard/frameworks#how-to-specify-a-target-framework), its seems one would specify `NETCOREAPP_OR_GREATER` (under DotNet 5+) but assume it would be something like ``netcoreapp3.1;net'`?

By no mean an expert here...

Thanks

**Comment by natemcmaster** [comment]
That constant only affects how this project compiles, and it only compiles for .NET Core 3.1 and 2.1.

https://github.com/natemcmaster/DotNetCorePlugins/blob/b1497f3a5c71e8ea553c5687604873b69515f651/src/Plugins/McMaster.NETCore.Plugins.csproj#L4

if you have decompiled source and are now viewing that file in the context of a new project which uses different frameworks and compile options, well then obviously it won’t compile the same.
