### ISSUE TITLE
Make plugins unloadable

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/DotNetCorePlugins#16]
This will require .NET Core 3.0 and up, which has added libraries to make assembly load contexts unloadable.

See https://github.com/dotnet/coreclr/issues/552, https://github.com/dotnet/coreclr/pull/18476, https://github.com/dotnet/corefx/issues/14724, and https://github.com/dotnet/coreclr/projects/9

**Comment by per-samuelsson** [comment]
Should be pretty straightforward to implement as well as it seem: [sample](https://github.com/dotnet/corefx/issues/19773#issuecomment-434520417).

Only 3.0 need to become available. 😎

**Comment by FrankDoersam** [comment]
Thank you for the info. However, after unloading, the DLL could not be deleted from the directory? Have I possibly ignored something?

Thanks in advance.
Yours sincerely
Frank Dörsam


Code:
 class SimpleUnloadableAssemblyLoadContext : AssemblyLoadContext
    {
        public SimpleUnloadableAssemblyLoadContext()
           : base(isCollectible: true)
        {
        }

        protected override Assembly Load(AssemblyName assemblyName) => null;
    }

    class Program
    {
        private static void ExecuteAssembly(Assembly assembly)
        {
            MethodInfo entry = assembly.EntryPoint;
            foreach (Type type in assembly.GetTypes())
            {
                Console.WriteLine(type.FullName);
            }
            Console.WriteLine("ok");

        }

        static void Main(string[] args)
        {
            AssemblyLoadContext tt = new SimpleUnloadableAssemblyLoadContext();
            tt.LoadFromAssemblyPath(@"C:\Lokale Daten\AppDomainUnload\ConsoleApp1\bin\Debug\netcoreapp3.0\Plugin\Plugin1.dll");

            tt.Unload();
            Console.ReadKey();
        }

        private static void Context_Unloading(AssemblyLoadContext obj)
        {
            Console.WriteLine("Unloading");
        }
    }

**Comment by natemcmaster** [comment]
If you are not able to delete a dll after unloading its load context, it is probably a bug in .NET Core 3. Checkout https://github.com/dotnet/coreclr/projects/9 to see if this is a known issue. If not, open a new bug on dotnet/coreclr.

**Comment by HamedFathi** [comment]
@natemcmaster,

Based on .NET Core 3 preview 1

![image](https://user-images.githubusercontent.com/8418700/50880880-229adb00-13f5-11e9-9487-230695b5ac2c.png)

Is this issue possible to solve now or need the next versions?

**Comment by natemcmaster** [comment]
Yes. 3.0 preview 1 should have AssemblyLoadContext.Unload in it. 

I don't think there is any use for MetadataLoadContext in this project. That API is more about "reflection-only" loading. It's similar to AssemblyLoadContext, but not exactly the same.

**Comment by natemcmaster** [comment]
Initial implementation #31.

## Usage
Unloadable plugins is supported in .NET Core 3.0 Preview 2 and newer. To unload a plugin, dispose the loader.

```c#
var loader = PluginLoader.CreateFromAssemblyFile(
                    pluginDll,
                    sharedTypes: new [] { typeof(IPlugin) });
// do stuff

loader.Dispose(); // this triggers an unload
```

**Comment by dazinator** [comment]
Any ideas whether this would allow asp.net core application parts to be unloaded (then reloaded from new assemblies) ? I asked raised an issue but the response was its not on asp.net core roadmap: https://github.com/aspnet/AspNetCore/issues/7219 - I wonder if you have had any thoughts around this?

**Comment by natemcmaster** [comment]
It might. Unloading is very new and I haven't played with it enough to try this out. Calling `.Dispose()` on a plugin doesn't guarantee it will be immediately unloaded. If managed memory still has pointers to something from the plugin, the plugin won't be cleaned up by garbage collection.

**Comment by natemcmaster** [comment]
Merged #31 which adds API when using .NET Core 3.0 to allow unloading.

## Usage
Unloadable plugins is supported in .NET Core 3.0 Preview 2 and newer. To unload a plugin, make sure isUnloadable = `true` and dispose the loader to trigger the unload.

```c#
var loader = PluginLoader.CreateFromAssemblyFile(
                    pluginDll,
                    sharedTypes: new [] { typeof(IPlugin) },
                    isUnloadable: true);
// do stuff

loader.Dispose(); // this triggers an unload
```

In order for this to work, you must make sure you have not left behind any variables (static, local, etc) or manually allocated memory. Once GC has collected everything, the assembly will be unloaded. See https://github.com/dotnet/coreclr/pull/22221

**Comment by dazinator** [comment]
Cool stuff. Is there a way to tell if a particular assembly has been unloaded? For example some kind of log output or something?

**Comment by natemcmaster** [comment]
There are some events triggered and you can also use a debugger. See https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability-howto
