### ISSUE TITLE
[Question] Loading Plugins of Plugin (Sub-plugins)?

### ISSUE THREAD

**Issue by aloksharma1** [natemcmaster/DotNetCorePlugins#160]
Hi,
i would like to know if its possible to do a dependency injections of sub plugins in a main plugin for example in a scenario like e-commerce checkouts where back-end user have multiple payment options (enabled/disabled) , is it possible to load those payment gateway plugins as a sub dependencies in the checkout form/other similar plugins as needed, and without writing them into core plugin?

something like this
-- sub-plugins SA,SB,SC,SD,SE...
-- plugin A 
    (requires sub plugin SA & SD ) <== inject as required
-- plugin B
    (requires sub plugin SA,SB & SE) <== inject as required

thanks

**Comment by Nikey646** [comment]
You would just need to implement the plugin loading functionality inside your plugin.

**Comment by aloksharma1** [comment]
can you explain a bit more? you mean like the given example of loading plugins on initiation (startup config)?

**Comment by Nikey646** [comment]
Yeah, when you load your plugin that wants subplugins, have the plugin create an instance of the plugin loader, configure it, and then load the subplugins.

**Comment by aloksharma1** [comment]
thanks that explains 1 part of the question, i will try that? what about the other part sharing these subplugins between plugins as shown in example scenario?

**Comment by Nikey646** [comment]
From my understanding of how this Plugin system works, that is not possible. You could have both Plugin A and Plugin B load SA each, but it won't be shared.

**Comment by aloksharma1** [comment]
so basically both be carrying a copy of subplugins, hmm this is not good for micro architecture

**Comment by natemcmaster** [comment]
Seems like a precarious architecture, but I don't think there is a technical restriction against this.  I've never tried myself, though, so your mileage may vary.
