### ISSUE TITLE
.net 5.0 rc 1.20 failure

### ISSUE THREAD

**Issue by Teknel** [natemcmaster/DotNetCorePlugins#161]
In the wpf application that I am making up to version .net 5.0 preview 7 the library worked correctly, but then with preview 8 and RC 1.20 it no longer compiles since the library says it is not compatible with .net 5.0.
Any suggestion?
Thank you very much.

**Comment by aloksharma1** [comment]
have you tried taking the source and recompiling the library itself with newer version?

**Comment by Teknel** [comment]
> have you tried taking the source and recompiling the library itself with newer version?

I have done that with others libraries before, but forgot to do with this.
Doing that I find my mistake.
I was not using the last Visual Studio 2019 Preview version.
Now with version 16.8.0 Preview 3.2 the library seems to work fine.

Thanks for your fast and accurate tip.
