### ISSUE TITLE
[Question] Plugin architecture for react or angular frontend apps? 

### ISSUE THREAD

**Issue by aloksharma1** [natemcmaster/DotNetCorePlugins#165]
i am using angular for a microservice net core application & this library for hosting plugins, i want to know if angular provides a plugin architecture system which we can use to create separate angular apps and then put them in main core app as pluggable modules.
so basically something similar to this library but for angular 8+ or react?
many thanks

**Comment by natemcmaster** [comment]
This is off topic for this project as Angular is an entirely different language and runtime environment.
