### ISSUE TITLE
[Question] System.BadImageFormatException: Could not load file or assembly when attempting to load plugins

### ISSUE THREAD

**Issue by tkennedy13** [natemcmaster/DotNetCorePlugins#166]
I have a Blazor Server app running on dotnet core 3.1. I'm trying to use DotNetCorePlugins to load some external dlls but I am getting a `System.BadImageFormatException` exception when attempting to load the plugins. I've used the samples for reference, but I must still be doing something wrong.

The full error I'm getting is:
System.BadImageFormatException: 'Could not load file or assembly 'MeanRevision, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)'

This is my startup method
   
        public Startup( IConfiguration configuration )
        {
            Configuration = configuration;

            // Load plugins (Algorithms)
            foreach ( var pluginDir in Directory.GetDirectories( Path.Combine( AppContext.BaseDirectory, "Algorithms" ) ) )
            {
                var dirName = Path.GetFileName( pluginDir );
                var pluginFile = Path.Combine( pluginDir, dirName + ".dll" );

                var loader = PluginLoader.CreateFromAssemblyFile( pluginFile,
                                                                  config => config.PreferSharedTypes = true );

                // System.BadImageFormatException: 'Could not load file or assembly 'MeanRevision, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)'
                foreach ( var type in loader.LoadDefaultAssembly()
                                            .GetTypes() // <- Error here
                                            .Where( t => typeof( IAlgorithm ).IsAssignableFrom( t ) && !t.IsAbstract ) )
                {
                    System.Diagnostics.Trace.WriteLine( "Found plugin " + type.Name );

                    var plugin = ( IAlgorithm ) Activator.CreateInstance( type );
                    _plugins.Add( plugin );
                }
            }
        }

This is the interface:

    public interface IAlgorithm
    {
        string GetName();
        Task Start();
        void Stop();
        void Configure( IApplicationBuilder appBuilder );
        void ConfigureServices( IServiceCollection services );
    }

and this is the implementation:

    internal class MeanRevision : IAlgorithm, IPlugin
    {
        public string GetName() => "Mean Revision";

        public Task Start()
        {
            throw new System.NotImplementedException();
        }

        public void Stop()
        {
            throw new System.NotImplementedException();
        }

        public void ConfigureServices( IServiceCollection services )
        {
            services.AddScoped<IAlgorithm, MeanRevision>();
        }

        public void Configure( IApplicationBuilder appBuilder )
        {
            throw new System.NotImplementedException();
        }
    }

I copied the dll into the correct location, but I must be missing something but I can't figure out what I'm doing wrong. Can someone please explain what I'm doing wrong?

**Comment by natemcmaster** [comment]
> Reference assemblies should not be loaded for execution. They can only be loaded in the Reflection-only loader context.

This probably means you're loading the wrong folder of .dll files. How did you create it? Did you use `dotnet publish`? If not, you probably harvested a folder filled with [reference assemblies](https://docs.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies)

**Comment by tkennedy13** [comment]
Thank you! I was not publishing the plugin,  I was just copying over the DLL. Once I published the plugin and copied everything over, the plugin loader was able to load the plugin and continue. Thank you for your help on this. I knew it was likely something I was doing wrong.
