### ISSUE TITLE
partManager.ApplicationParts.Remove,Releases the current assembly related services

### ISSUE THREAD

**Issue by tanyo520** [natemcmaster/DotNetCorePlugins#174]
Through_ partManager.ApplicationParts.Remove (_ After removing the assembly, install the assembly again, and find HttpContext.RequestServices The services of application services are not released, or the previous services are used. Is there any good way to release the services of the current assembly when uninstalling
![image](https://user-images.githubusercontent.com/5094034/105157539-0a173c80-5b48-11eb-8c07-d1c396a6cf66.png)
![image](https://user-images.githubusercontent.com/5094034/105157558-100d1d80-5b48-11eb-8cfd-9dce4d7d7c77.png)

**Comment by natemcmaster** [comment]
It looks like you're trying to do reloading of plugins with MVC, right? If so, I haven't seen this successfully done due to the design of ASP.NET itself. As far as I know, MVC and reloading are not possible, so you have to restart the process completely to get a new version of a plugin.
