### ISSUE TITLE
How do I create automated migration for Plugin Tables ? [Question] 

### ISSUE THREAD

**Issue by beslamirad** [natemcmaster/DotNetCorePlugins#193]
hi dear ,
first see this figure

![migrations](https://user-images.githubusercontent.com/26228300/107121831-bfb4f000-68a9-11eb-9475-3ec7a1f42e8f.jpg)

i create a Simple Host Weblog with **DataContext** and 2 table
and want load plugin2 to host, (So far no problem)

Now , Ho To Add Plugins Table to Main DbContext ?
without add migration and ...
just Dynamic.

tanks

**Comment by aloksharma1** [comment]
Hi,
Hope this helps [adding models to existing dbcontext](https://stackoverflow.com/questions/39834506/adding-new-models-to-an-existing-context-at-runtime-in-entity-framework)  Also there is also this open source e-commerce project that uses similar method [SimplCommerce](https://github.com/simplcommerce/SimplCommerce) which i am reading to figure out the principals behind sharing context b/w plugins and automagic migrations. also I am working on similar issues right now, so if you solve it first please share a sample repo on git.
And if i get to solve it first, I will share mine ;)

Happy coding

**Comment by beslamirad** [comment]
I can solve it, but mix Ef6 and Efcore

**Comment by aloksharma1** [comment]
i lost you here :"but mix Ef6 and Efcore" if you meant that you are using both ef6 and core versions then no you cant mix these 2 dbcontexts as they are running on essentially different versions/techs.
as for this "How To Add Plugins Table to Main DbContext"
i solved it by extending main DbContext class to plugins and overriding their own configurations as needed.

**Comment by beslamirad** [comment]
In i solve all querys,insert, update , select and .... Execute via Efcore that use genericRespository ,but add tables and add migration and update-database used Ef6 db context Automatic , 
*** both dbContext ModelBuilder send to plugin for add tables
*** Do you can Share Simple code from your sloved

**Comment by aloksharma1** [comment]
Hi,
I have solved the issues and created a minimal sample.. I will upload it by tomorrow if I am free.. i will update my project repo link here.

**Comment by aloksharma1** [comment]
here is the library example i created, it solves following issues:
- multiple type of db providers (sql & mysql currently)
- loading context models into core context from plugins
- automatic migrations
- apply/remove migrations on plugin install/uninstall 
- DataSeeding
- can be enhanced for automatic migration generation too

https://github.com/aloksharma1/DBInjectionWithMultiProviders
the readme file is not updated yet as i have little time to work on other stuff these days, but here it is the code is clean and follow solid/clean architecture principals (i removed infra & service layers to reduce complexity).
hope this helps others too
