### ISSUE TITLE
Unable to debug code loaded in more than one ALC

### ISSUE THREAD

**Issue by per-samuelsson** [natemcmaster/DotNetCorePlugins#20]
Consider this setup:

* Library1
* Plugin1 (depend on Library1, via project reference)
* Plugin2 (depend on Library1, via project reference)
* Host (console app)

Host is using `PluginLoader.CreateFromAssemblyFile(pluginPath)` to load both plugin assemblies, and calls a "startup" method in them. Plugins call a common method in `Library1`.

No shared types and no custom options in use.

If I debug the host, I can step Host -> Plugin -> Library1 when the **first** plugin is loaded. But when the second one is, I can **not** step into method of Library1. Also, I see a message (in Debug Output) that `Library1` from path of `Plugin` can't load. (Using VS Code to debug, but tested VS 17 too). That part is also confusing, since why shouldn't it load in the second ALC?

Let me know if you want me to craft a repro.

**Comment by natemcmaster** [comment]
This seems like a bug in .NET Core itself and the way AssemblyLoadContext works. This library doesn't do anything special with symbols, or do anything to prevent symbols from loading. If there is something this library needs to do to help IDE's find symbols, I'm happy to add that, but I don't know what that would be.

I would recommend opening a bug on github.com/dotnet/core to see if the coreclr team can help with this.

**Comment by per-samuelsson** [comment]
Spent some time testing a few things with just using regular ALC API today, and found some interesting facts:

1. I can observe the same behavior there.
2. I can get get *pass* that behavior there by using `LoadFrom` instead of `LoadFile`. With `LoadFrom`, the debugging works as expected.

I recon then `AssemblyLoadContext.LoadFromAssemblyPath` uses `LoadFile`.

With that, I think I can take it (with my repro) to core team.

**Comment by natemcmaster** [comment]
Thanks for sharing. I'm going to close this in favor of https://github.com/dotnet/coreclr/issues/20607

**Comment by per-samuelsson** [comment]
In case it can help anyone getting here and still looking for answers:

https://github.com/dotnet/coreclr/issues/20607#issuecomment-456103787
