### ISSUE TITLE
System.PlatformNotSupportedException: 'Strings.PlatformNotSupported_DataSqlClient'

### ISSUE THREAD

**Issue by HamedFathi** [natemcmaster/DotNetCorePlugins#215]
**Describe the bug**
When I run the following code in a simple app like console everything is fine but when I call it from plugin via plugin loader throws an error.

```
System.PlatformNotSupportedException
  HResult=0x80131539
  Message=Strings.PlatformNotSupported_DataSqlClient
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at TablePlugin.TableMaker.GetSQServerTables(String connStr)
```

the code is

```cs
using Microsoft.Data.SqlClient;

private string[] GetSQServerTables(string connStr)
{
    var tables = new List<string>();

    using var connection = new SqlConnection(connStr); // EXCEPTION IS HERE
    connection.Open();
    var command = connection.CreateCommand();
    command.CommandText = "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY TABLE_NAME";
    using var reader = command.ExecuteReader();
    while (reader.Read())
    {
        tables.Add(reader.GetString(0));
    }

    return tables.ToArray();
}
```

**To Reproduce**
You have access to my repo from [here](https://github.com/dotnet-toolbelt/Gravity)

**Expected behavior**
I expect to load the plugin without a problem. 

**Screenshots**
<img width="878" alt="Screenshot_1" src="https://user-images.githubusercontent.com/8418700/121803390-9fbf7f80-cc41-11eb-9ce3-6325fb045597.png">

Any solution?

**Comment by natemcmaster** [comment]
Try changing your plugin to use `<TargetFramework>net5.0</TargetFramework>` instead of netstandard.
