### ISSUE TITLE
[Question] Blazor Server App example

### ISSUE THREAD

**Issue by XeroVice** [natemcmaster/DotNetCorePlugins#225]
Hello,

I just found this a few hours ago and currently I'm trying to get this running for Blazor Server App.
I successfully managed to get the loader working and loading the plugin, but the page I'm trying to load in is not available.

Loading classes works fine, but how can I dynamicly hot reload and load the .razor file too?

Thanks in advance and sorry if this might be trivial.

**Comment by natemcmaster** [comment]
I don’t know. I have not looked at how the internals of Blazor works. This project doesn’t explicitly support Blazor, but it also doesn’t do anything to block you from building your own support for Blazor. I’m closing, however, as supporting Blazor is not something I plan to spend any time doing. If you (or anyone else reading this later) wants to support a library that integrates this project and Blazor, I’d be happy to link to it from the README
