### ISSUE TITLE
Could this work with .net 4.6+?

### ISSUE THREAD

**Issue by vdurante** [natemcmaster/DotNetCorePlugins#23]
Hey, I really enjoyed using this lib with dotnet core, but I really need to make something similar for .net 4.6. Would this work if I built it for 4.6? Thanks

**Comment by natemcmaster** [comment]
This relies on an API -- [System.Runtime.Loader.AssemblyLoadContext](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext) -- with is .NET Core only. So, no, sorry.
