### ISSUE TITLE
[Question] Is it possible to isolate plugin configuration to different json configuration file?

### ISSUE THREAD

**Issue by NewHeight** [natemcmaster/DotNetCorePlugins#232]
There are two Plugins, WebPlugin1 and WebPlugin2. And there are some seperate configuration related to these two plugins. Can I has two plugin configuration file like WebPlugin1.json and WebPlugin2.json for plugin configuration seperately?
Thanks

**Comment by natemcmaster** [comment]
This question doesn't have a lot of detail for me to provide a better answer, so I'll just re-iterate the guidance on multiple plugins [from the README](https://github.com/natemcmaster/DotNetCorePlugins/blob/main/README.md#the-host) and putting them into separate directories.

>
>One way to do this is to follow a convention, such as:
>
>```
> plugins/
>     $PluginName1/
>         $PluginName1.dll
>         (additional plugin files)
>     $PluginName2/
>         $PluginName2.dll
>```
> 
> It is important that each plugin is published into a separate directory. This will avoid contention between plugins and duplicate dependency issues.

Hope that helps
-Nate
