### ISSUE TITLE
[Question] Does hot reload work for aspnetcore plugins with service registration?

### ISSUE THREAD

**Issue by NewHeight** [natemcmaster/DotNetCorePlugins#233]
Hi, I has a aspnetcore plugin with service registration into the ServiceCollection, does it has any method to re-register the service when the plugin reload?

**Comment by natemcmaster** [comment]
No such method or feature exists. The hot reload capability is pretty bare-bones and doesn't work with ASP.NET Core's dependency injection setup, which is immutable after the service container is initialized.

Hope that helps,
Nate
