### ISSUE TITLE
Net 6 Support - Minimal API

### ISSUE THREAD

**Issue by Simonl9l** [natemcmaster/DotNetCorePlugins#236]
**Is your feature request related to a problem? Please describe.**
With the release of Net 6.0 and [Minimal API](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0)  it would be great to have the equivalent of the [Support for MVC and Razor](https://github.com/natemcmaster/DotNetCorePlugins#support-for-mvc-and-razor) in an environment that no longer has a `Startup`. and allows an easy way to hookup classes that provide extension to `IEndpointRouteBuilder`.

**Describe the solution you'd like**
As above, such that one could:
```C#
 var app = WebApplication.CreateBuilder().Build();
 app.MapPluginFromAssemblyFile(pluginFile)

```
**Describe alternatives you've considered**
None yet

**Additional context**
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0

**Comment by natemcmaster** [comment]
I would be willing to accept a pull request for this.
