### ISSUE TITLE
.NET Standard Support?

### ISSUE THREAD

**Issue by adospace** [natemcmaster/DotNetCorePlugins#24]
**Is your feature request related to a problem? Please describe.**
I'd like to use the library from a shared .net standard project

**Describe the solution you'd like**
Use the library from a .NET Standard project

**Describe alternatives you've considered**
In a complex project, we have more than one .net core applications that load plugins. I'd like to share the plugin loader code in a .NET standard project. Right now the only solution possible is to duplicated plugin loading in all core apps?

BTW great project!

**Comment by natemcmaster** [comment]
Sorry -- can't do this one. The most important part of this project depends on an API System.Runtime.Loader.AssemblyLoadContext which is not supported in .NET Standard or .NET Framework. So, this project is intentionally only for .NET Core.

**Comment by adospace** [comment]
Sorry, I don't want to bother, I want to just point out that System.Runtime.Loader.AssemblyLoadContext is available in a nuget package System.Runtime.Loader.
Just for test I've added that package:
`<PackageReference Include="System.Runtime.Loader" Version="4.3.0" />`
and target netstandard:
`<TargetFramework>netstandard2.0</TargetFramework>`
Rebuilding all without errors, tests also succed.

Now I suppose that this won't work if this library is linked to a full .net project but at least in the above scenario I describe why not?

**Comment by natemcmaster** [comment]
It's a good question. You've found one of the more obscure mistakes in .NET Standard 1.x packaging. Checkout this thread https://github.com/dotnet/corefx/issues/22142#issuecomment-444583754. Even though things look okay to the C# compiler, when you run a .NET Framework app, it will always fail with an error like this: `FileNotFoundException: Could not load file or assembly 'System.Runtime.Loader'`.
