### ISSUE TITLE
Microsoft.Data.SqlClient is not supported on this platform

### ISSUE THREAD

**Issue by zraffaele** [natemcmaster/DotNetCorePlugins#243]
Hi,
in a method of plugin when create a connection i've this error.
If i try to execute the same code in the hoster i don't encure in this error.
Where is the my issue?
Thank you.

**Comment by aloksharma1** [comment]
can you add some code? my first guess is maybe its your DI thats not configured correctly, but without code we wont know a thing.

**Comment by Victhy** [comment]
I had the same problem. Have you solved it yet? @zraffaele

**Comment by ramonsmits** [comment]
After posting my last comment I just tested my last comment to probe for frameworks in a certain order and that works beautifully for our usage. I updated the gist.
