### ISSUE TITLE
[Question] .NET6 System.InvalidOperationException Hostpolicy must be initialized 

### ISSUE THREAD

**Issue by wingchunninja** [natemcmaster/DotNetCorePlugins#247]
I have moved my project from .netcore2.1 to .net6. I have also updated the DotNetCorePlugins package to 1.4.0.

When calling this line, I am also getting the following error:
`PluginLoader pluginLoader = PluginLoader.CreateFromAssemblyFile(pluginPath, typeof(IPlugin).Assembly.GetTypes());`

`Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'Dependency resolution failed for component ..... with error code -2147450750. Detailed error: Hostpolicy must be initialized and corehost_main must have been called before calling corehost_resolve_component_dependencies.`

Have you experienced something like this?

My Plugin Project ist netstandard 2.0 and the main app is .net6.

**Comment by natemcmaster** [comment]
Try compiling the plugin for net6.0, not netstandard2.0. Netstandard has known issues.

**Comment by wingchunninja** [comment]
The Plugin needs to be working as a netstandard one. Before moving to .net 6, I didn't have any issues with it. But since then I have been getting the exception from above. 

I am testing this on a macOS.
