### ISSUE TITLE
Plugin that uses managed Sql client library won't allow unloading the assembly

### ISSUE THREAD

**Issue by lucashby** [natemcmaster/DotNetCorePlugins#249]
**Describe the bug**
I am using the managed Sql client library (Microsoft.Data.SqlClient version 4.1.0) in a plugin, but doing so doesn't allow the loader to unload the context.

**To Reproduce**
1. Please see my GH repo that reproduces the issue here, https://github.com/lucashby/plugins
2. The console spits out at the end if the WeakReference is still alive, and it is but shouldn't be

**Expected behavior**
I would expect with the SqlConnection.ClearAllPools() and the AppContext switch they added for the SqlClient to force usage of the managed client, even on Windows, for the loader to unload the plugin assembly.

EDIT: spelling

**Comment by natemcmaster** [comment]
This is beyond this project's ability to fix. This is an issue in the .NET runtime itself and how it handles unloading of native assemblies (e.g. you can't unload native dependencies). You will need to request help from .NET for this.
