### ISSUE TITLE
[Question] Using subdirectories within a plugin directory?

### ISSUE THREAD

**Issue by lonnietc** [natemcmaster/DotNetCorePlugins#250]
Hello,

I have recently come across the DotNetCorePlugins repository and it looks like it might be perfect for the project that I am working on now which will have a basic core application and pretty much all of the additional functionality will be provided by having a plugin.

In as much, I see that the recommend layout is:

```
plugins/
    $PluginName1/
        $PluginName1.dll
        (additional plugin files)
    $PluginName2/
        $PluginName2.dll
```

but I am wondering if that could be extended further, to be like:

```
plugins/
    $PluginName1/
        $PluginName1.dll
              $PluginName1Sub/
              (additional plugin files)
    $PluginName2/
        $PluginName2.dll
              $PluginName2Sub/
              (additional plugin files)
```

So that there is a sub-directory within each Plugin directory for their application support files to be place and within the main Plugin subdirector would be just specific configuration files or documentation files, etc. (for example) for that particular plugin but the plugin application files would be in its own one-level deeper subdirecotry.

That is the idea at least to keep think clean and organized.

can this be done?

**Comment by natemcmaster** [comment]
You can definitely create your own subfolders within plugins. Nothing about this library prescribes that configuration files, docs, etc. need to be siblings of the main .dll file for the plugin.
