### ISSUE TITLE
[Question] Can you load same named assembly as plugin but different version?

### ISSUE THREAD

**Issue by GammaSoul** [natemcmaster/DotNetCorePlugins#253]
Hi there im new to this plugin, it looks amazing! just one question is it possible to load plugins with the same name but a different version? 
Like setting assembly info Version and this famework can load and read the version of that plugin but will only load one of each version. you could also activate and deactivate versions and access a plugin based on the version from the rest of the application.
Something like this would enable hot version control & upgrade / downgrade of a running application.

**Comment by MICHAELHANNA-GEP** [comment]
I am on the same boat .. @GammaSoul  did you find a way to load multiple version ?

**Comment by GammaSoul** [comment]
> I am on the same boat .. @GammaSoul did you find a way to load multiple version ?

Hi mate sorry for the late reply. I think its just not possible to do it. So what i am working on is basically creating an MSbuild workflow based on the major/minor version of the plugin assembly that will change the assembly name to include the major and minor version at the end of the plugin name. Doing it this way you can use what is the same functional assembly but with different names. Its Also a good and easy way to keep track of versions.  I will also add a way to automatically copy over (or create symlink for) the files to a directory stucture that includes the plugin based on version and any resources/dlls that it needs so that the main application can easyload the plugin when you build the solution. When i get around to it I will post what ive done for others to use or get an idea from.

**Comment by MICHAELHANNA-GEP** [comment]
keep me posted !
