### ISSUE TITLE
Use WeakReference to check if unload is successful

### ISSUE THREAD

**Issue by Sardelka9515** [natemcmaster/DotNetCorePlugins#259]
As pointed out in readme, the unload is performed asynchronously and won't always be successful, maybe we can use a `WeakReference` to guarantee the unload is successful before the loader is disposed, otherwise throw an exception. 
There's also an example implementation in the [dotnet samples](https://github.com/dotnet/samples/blob/main/core/tutorials/Unloading/Host/Program.cs) repository if you're interested.

**Comment by Tbeck-91** [comment]
this would be very useful
