### ISSUE TITLE
Error while loading unmanaged dlls

### ISSUE THREAD

**Issue by maxacoustic** [natemcmaster/DotNetCorePlugins#26]
"CreateFromPackage" method defined in "NativeLibrary" class sets the native library name as a library's dll name without extension (https://github.com/natemcmaster/DotNetCorePlugins/blob/91b44684f5f696cc7c51d4eae1081e339ff77a15/src/Plugins/LibraryModel/NativeLibrary.cs#L56).

This name is used by "AssemblyLoadContextBuilder" in "AddNativeLibrary" method as a key for a "_nativeLibraries" dictionary (https://github.com/natemcmaster/DotNetCorePlugins/blob/91b44684f5f696cc7c51d4eae1081e339ff77a15/src/Plugins/Loader/AssemblyLoadContextBuilder.cs#L158) wich later passed to the "ManagedLoadContext" constructor.

"ManagedLoadContext" class defines "LoadUnmanagedDll(string unmanagedDllName)" method to proccess unmanaged dll requests (https://github.com/natemcmaster/DotNetCorePlugins/blob/91b44684f5f696cc7c51d4eae1081e339ff77a15/src/Plugins/Loader/ManagedLoadContext.cs#L113). This method trying to get "NativeLibrary" instance from "_nativeLibraries" dictionary, using platform related prefixes + "unmanagedDllName".

"unmanagedDllName" argument of "LoadUnmanagedDll" may contain both library name and library file path (absolute or relative). In second case (for example, https://github.com/dotnet/corefx/blob/8f7b490ca874ee2a9f11f0163412f7c95811298b/src/System.Data.SqlClient/src/Interop/SNINativeMethodWrapper.Windows.cs#L183
```C#
private const string SNI = "sni.dll";
...
[DllImport(SNI, CallingConvention = CallingConvention.Cdecl, EntryPoint = "SNIAddProviderWrapper")]
internal static extern uint SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, [In] ref uint pInfo);
```
) "LoadUnmanagedDll" method will fail.

It seems that trimming path and extensions from "PlatformInformation.NativeLibraryExtensions" in "unmanagedDllName" is appropriate here. Or better "Path.GetFileNameWithoutExtension" call as it works in "NativeLibrary.CreateFromPackage".

Hope my description is understoodable.

**Comment by natemcmaster** [comment]
I'm not 100% sure I understand. Are you proposing a change? Are you running into an error? If so, can you share steps to reproduce?

**Comment by maxacoustic** [comment]
Let we have a plugin:
```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.6.0" />
  </ItemGroup>
</Project>
```
```C#
using System;
using System.Data;
using System.Data.SqlClient;

namespace Sample.Plugin
{
    public class PluginEntry
    {
        public void DoPluginWork()
        {
            var connectionStr = "Data Source=.\\sqlexpress;Integrated Security=SSPI;Initial Catalog=SampleDb";
            using (var connection = new SqlConnection(connectionStr))
            {
                if (connection.State != ConnectionState.Open) connection.Open();
                using (var command = new SqlCommand("[Sample].[StoredProcedure]", connection) { CommandType = CommandType.StoredProcedure })
                {
                    using (var reader = command.ExecuteReader())
                    {
                        var dataOrdinal = reader.GetOrdinal("Data");
                        while (reader.Read())
                        {
                            Console.WriteLine(reader.GetString(dataOrdinal));
                        }
                    }
                }
            }
        }
    }
}
```
, and plugin loader:
```C#
using System;
using System.IO;
using System.Linq;
using McMaster.NETCore.Plugins;

namespace Sample.PluginLoader
{
    class Program
    {
        static void Main(string[] args)
        {
            Directory.SetCurrentDirectory(AppDomain.CurrentDomain.BaseDirectory);
            var pluginPath = Path.GetFullPath(@"plugin/Sample.Plugin.dll");
            var loader = McMaster.NETCore.Plugins.PluginLoader.CreateFromAssemblyFile(pluginPath, PluginLoaderOptions.None);
            var pluginType = loader.LoadDefaultAssembly().GetExportedTypes().Single(t => t.Name == "PluginEntry");
            var instance = Activator.CreateInstance(pluginType);
            var method = pluginType.GetMethod("DoPluginWork");
            method.Invoke(instance, new object[0]);
            Console.ReadKey();
        }
    }
}
```

Build script:
```
dotnet build -r win-x64 -c Debug -o ../loader Sample.PluginLoader\Sample.PluginLoader.csproj
dotnet build -r win-x64 -c Debug -o ../loader/plugin Sample.Plugin\Sample.Plugin.csproj
```
Executing plugin loader causes System.DllNotFoundException: 
```
'Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)'
```
in PluginEntry class while executing
```C#
if (connection.State != ConnectionState.Open) connection.Open();
```
This happens because Sample.Plugin depends on System.Data.SqlClient, wich imports native library "sni.dll" using DllImportAttribute with relative path as a parameter.
```C#
private const string SNI = "sni.dll";
...
[DllImport(SNI, CallingConvention = CallingConvention.Cdecl, EntryPoint = "SNIAddProviderWrapper")]
internal static extern uint SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, [In] ref uint pInfo);
```

The reason of this error is described in my first message: dotnet allows to import native dlls using DllImportAttribute and both absolute and relative path to dll as its argument. But at this moment your PluginLoader handles such situations wrong.

This is a bug.

**Comment by dferretti-fig** [comment]
Have you tried `dotnet publish` instead of `dotnet build`?

**Comment by maxacoustic** [comment]
After plugin publishing it works well, because call `base.LoadUnmanagedDll(unmanagedDllName);` in `ManagedLoadContext.LoadUnmanagedDll` method loads relative path "sni.dll" normally from the plugin dir. 
In case of framework-dependent deployment relative path "sni.dll" not exists for "System.Data.SqlClient.dll",  because them both located in different paths. This cause an exception. And this case shold be handled by overrided LoadUnmanagedDll, but it is not, because `_nativeLibraries` dictionary contains "sni" as a key, but not a "sni.dll".
![2019-01-14 13_49_59-dotnetcoreplugins debugging - microsoft visual studio administrator](https://user-images.githubusercontent.com/3940448/51108490-4fcafd00-17ea-11e9-8004-87310cc10819.png)

**Comment by maxacoustic** [comment]
Another funny moment: if I'm adding `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` property to plugin project and building it using `dotnet build`, it also gets a copy of sni.dll, but `base.LoadUnmanagedDll` fails in this case and `connection.Open();` cause the DllNotFoundException.

Content of the plugin folder in this case is same as it's content after `dotnet publish` except extra dotnetcoreapp host files ("apphost.exe, hostfxr.dll, hostpolicy.dll"). ".deps.json" files are also same.

I have no idea why this happens. @dferretti-fig, @natemcmaster maybe you have?

**Comment by natemcmaster** [comment]
@maxacoustic give this build of the package a try and let me know if it you still have issues.

https://www.myget.org/feed/natemcmaster/package/nuget/McMaster.NETCore.Plugins/0.2.2-rtm.40

**Comment by maxacoustic** [comment]
Now it works proper in all cases I described. Thank you!
