### ISSUE TITLE
Docker file build problems

### ISSUE THREAD

**Issue by OrionRiftStudios** [natemcmaster/DotNetCorePlugins#265]
Hello, 
I am using this plugin with Blazor Server.
It is working perfectly!
I am using docker file but I cannot build anymore the project when I want to create the docker image.

I am having some issues trying to fix this problem 

this is the current configuration I the host project:

 <Target Name="PublishPlugins" BeforeTargets="Build">

        <ItemGroup>
            <PluginProject Include="..\Plugins\UI\Store\SolarFist.Blazor.Plugins.UI.Store.NftDetails\SolarFist.Blazor.Plugins.UI.Store.NftDetails.csproj" />
            <PluginProject Include="..\Plugins\UI\Store\SolarFist.Blazor.Plugins.UI.Store.MyNfts.Default\SolarFist.Blazor.Plugins.UI.Store.MyNfts.Default.csproj" />
            <PluginProject Include="..\Plugins\UI\Store\MyNfts.Sections\SolarFist.Blazor.Plugins.UI.Store.MyNfts.OwnedNfts\SolarFist.Blazor.Plugins.UI.Store.MyNfts.OwnedNfts.csproj"></PluginProject>
            <PluginProject Include="..\Plugins\UI\Store\SolarFist.Blazor.Plugins.UI.Store.Default\SolarFist.Blazor.Plugins.UI.Store.Default.csproj" />
            <PluginProject Include="..\Plugins\UI\SolarFist.Blazor.Plugins.UI.Analytics.Core\SolarFist.Blazor.Plugins.UI.Analytics.Core.csproj" />
            <PluginProject Include="..\Plugins\UI\SolarFist.Blazor.Plugins.UI.Analytics.Default\SolarFist.Blazor.Plugins.UI.Analytics.Default.csproj" />
            <PluginProject Include="..\Plugins\UI\SolarFist.Blazor.Plugins.UI.Analytics.Basic\SolarFist.Blazor.Plugins.UI.Analytics.Basic.csproj" />
            <PluginProject Include="..\Plugins\UI\SolarFist.Blazor.Plugins.UI.Analytics.Advanced\SolarFist.Blazor.Plugins.UI.Analytics.Advanced.csproj" />
        </ItemGroup>

        <MSBuild Projects="@(PluginProject)" Targets="Publish" Properties="PublishDir=$(TargetDir)plugins\%(FileName)\" />
    </Target>

This configuration is working locally but using the docker file I am getting this error.
/usr/share/dotnet/sdk/6.0.401/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1004: Assets file '/src/src/Plugins/UI/Store/SolarFist.Blazor.Plugins.UI.Store.NftDetails/obj/project.assets.json' not found. Run a NuGet package restore to generate this file. [/src/src/Plugins/UI/Store/SolarFist.Blazor.Plugins.UI.Store.NftDetails/SolarFist.Blazor.Plugins.UI.Store.NftDetails.csproj]

I hope someone could help me to solve this issue. thanks

**Comment by dheerajawale-svg** [comment]
I tried with 2.0.0-beta.130. Its working for me using default Dockerfile generated by Visual Studio
