### ISSUE TITLE
[Question] How to inject Logger or IConfiguration in Plugins ? I tried and failed

### ISSUE THREAD

**Issue by asdge245871623** [natemcmaster/DotNetCorePlugins#284]

**Comment by asdge245871623** [comment]
plugins loader ：
`foreach (var pluginDir in Directory.GetDirectories(Path.Combine(AppContext.BaseDirectory, "Drivers")))
            {
                var dirName = Path.GetFileName(pluginDir);
                var pluginFile = Path.Combine(pluginDir, dirName + ".dll");
                var loader = PluginLoader.CreateFromAssemblyFile(pluginFile,
                    // this ensures that the plugin resolves to the same version of DependencyInjection
                    // and ASP.NET Core that the current app uses
                    sharedTypes: new[]
                    {
                        typeof(IIoTPlugins),
                        typeof(IServiceCollection),
                        typeof(ILogger)
                    });
                foreach (var type in loader.LoadDefaultAssembly()
                             .GetTypes()
                             .Where(t => typeof(IIoTPlugins).IsAssignableFrom(t) && !t.IsAbstract))
                {
                    Console.WriteLine("Found plugin " + type.Name);
                    var plugin = (IIoTPlugins)Activator.CreateInstance(type);
                    plugin?.ConfigureServices(services);
                }
            }`

**Comment by aloksharma1** [comment]
where are you getting this issue? can you share a bit of startup code, please note plugins in mvc requires mvc plugin loader to register extra services.
