### ISSUE TITLE
Add support for resolving a plugin from NuGetv3

### ISSUE THREAD

**Issue by psibernetic** [natemcmaster/DotNetCorePlugins#3]
**Is your feature request related to a problem? Please describe.**
My scenario is a platform-styled server application that uses "Connectors" to act on a workflow. As of now, the server has to be recompiled with the appropriate connectors. This library enables me to use the plugin model which is fantastic, but still requires manually deploying the plugins to the server. It's certainly workable.

**Describe the solution you'd like**
I'd like a method that would, given a nuget packageId and optionally version, download & install the plugin and do the same for any unresolved dependencies, so that it could be loaded by this library. 

**Describe alternatives you've considered**
The alternative is to do all the heavy lifting with NuGet in a separate library specialized for that, and then load the plugin as a step 2.

**Additional Context**
The NuGet feed I would resolve the plugin from would be secured & trusted for code execution security purposes. The dependent packages could resolve from either feed.

**Comment by psibernetic** [comment]
Thanks, I'll go ahead and close this then, think it helps define the scope!

**Comment by Jericho** [comment]
I'm sad that this issue was closed. I think it would be fantastic to be able to resolve dependencies to their respective nuget package.

**Comment by natemcmaster** [comment]
Just to clarify, the loader is already capable of resolving assemblies out of the NuGet cache. What I'm not planning to fix, however, is a feature to place packages into the NuGet cache as your app is running. I believe that's a behavior better left to the .NET SDK. It would be very difficult to implement this without basically just running `Process.Start("dotnet", "restore")`.

**Comment by Jericho** [comment]
When developers write plugins for my app they will most likely reference nuget packages that may or may not be present on the end-user's machine. If this library does not fetch the missing packages, that means that my app must do it right? (or I could ask developers to refrain from using nuget packages at all, but I'm afraid that would not be well received).

Do you have suggestions how we could go about discovering the missing packages that a given plugin depends on?

**Comment by natemcmaster** [comment]
I would recommend developers writing plugins for your app use `dotnet publish` to gather the plugin, and its dependencies, into a single folder. How developers bundle up that folder, distribute it, and how your app finds the plugin is still up to you. I'm open to discussing solutions for those problems -- one of those solutions might involve NuGet -- but providing a general solution for those problems is not a top priority.
