### ISSUE TITLE
Plugin config not generating

### ISSUE THREAD

**Issue by csnewman** [natemcmaster/DotNetCorePlugins#30]
**Describe the bug**
Using the plugins.sdk, when publishing or building, the plugin.config file is not generated. Not sure whether this is a documentation issue or a bug.

**To Reproduce**
Steps to reproduce the behavior based on the readme file:
1. Create a new .net standard class library in VS Studio
2. Change csproj file to
``` 
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <IsPlugin>true</IsPlugin>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="McMaster.NETCore.Plugins.Sdk" Version="*" />
  </ItemGroup>
</Project>
```
3. Publish via
```
dotnet publish MyPlugin1.csproj --output plugins/MyPlugin1/
```

**Expected behavior**
A plugin.config file should be generated in the output directory.

**Comment by natemcmaster** [comment]
Can you add `-binaryLogger` to the `dotnet publish` command and share the `msbuild.binlog` file it creates?

**Comment by qumeta** [comment]
[msbuild.zip](https://github.com/natemcmaster/DotNetCorePlugins/files/2811859/msbuild.zip)
the same problem, this is a sample binlog

**Comment by natemcmaster** [comment]
Give this a try: https://www.nuget.org/packages/McMaster.NETCore.Plugins.Sdk/0.2.3

**Comment by qumeta** [comment]
[msbuild.zip](https://github.com/natemcmaster/DotNetCorePlugins/files/2815340/msbuild.zip)
it worked ,i find the plugin.config. but i got three plugin.config files. 
![dot](https://user-images.githubusercontent.com/1006196/52024736-d4cd4a80-253c-11e9-93b0-8f50273cd31b.jpg)

**Comment by natemcmaster** [comment]
Thanks for reporting. That's a different bug which I think is fixed with this change https://github.com/natemcmaster/DotNetCorePlugins/commit/c5b9a5d2bd1be7aa738daeb799c4928e00163f39. Give this build a try. If it fixes the problem, I'll release to nuget.org as 0.2.4.

https://www.myget.org/feed/natemcmaster/package/nuget/McMaster.NETCore.Plugins/0.2.4-preview.190130.2

```
PM> Install-Package McMaster.NETCore.Plugins -Version 0.2.4-preview.190130.2 -Source https://www.myget.org/F/natemcmaster/api/v3/index.json
```

**Comment by qumeta** [comment]
yes,  0.2.4-preview.190130.2 look good for me. good job. @natemcmaster  👍

**Comment by natemcmaster** [comment]
Thanks for verifying. I'll release to nuget.org.
