### ISSUE TITLE
PluginLoader - No option to load from existing PluginConfig

### ISSUE THREAD

**Issue by dazinator** [natemcmaster/DotNetCorePlugins#32]
**Is your feature request related to a problem? Please describe.**
`PluginLoader` has a load from config file method that takes a string which is a file path. 
However that implementation is coupled to the physical file system (system.io.file, system.io.directory etc) - I'd like to be able to load `PluginLoader` from a config file provided as a stream.

**Describe the solution you'd like**
`PluginConfig` itself can already be loaded from a stream, I think PluginLoader just needs a factory method that is capable of taking an existing PluginConfig instance rather than always creating a new one based on file path. 

**Describe alternatives you've considered**
Tried to construct my own instance of Plugin Loader - but the constructor is internal forcing use of the static factory methods available.

**Additional context**
I'm approaching plugin loading trying to limit all file system interactions to go via an `IFileProvider` abstraction. Which means any methods which go directly via System.IO.File or Directory are no good to me - so I am looking for alternatives that allow me to provide streams etc.

**Comment by natemcmaster** [comment]
I would take a PR to add an overload for this scenario.

**Comment by dazinator** [comment]
active
