### ISSUE TITLE
Consider adopting IFileProvider abstraction for all file system interactions

### ISSUE THREAD

**Issue by dazinator** [natemcmaster/DotNetCorePlugins#33]
**Is your feature request related to a problem? Please describe.**
In various places, system.io namespace is used to check check for folders / files and read files into memory. These means there is no level of indirection for file access.
 
**Describe the solution you'd like**
I would like to provide an IFileProvider to be used for all file system access  (Microsoft.Extensions.FileProviders). The benefit of this, to me, is that there are many different implementations of IFileProvider that could be swapped out as needed. For example, for testing, I could use an InMemory IFileProvider (stage in memory streams for plugins and config files). At application run time, I could use the PhysicalFileProvider from `IHostingEnvironment` or perhaps provide an `AzureBlobStorageFileProvider` or `7ZipArchiveFileProvider` (there are some IFileProviders that allow you to effectively mount zip archives as a file system which could be useful if you want to download plugins as zip files, and want to keep them compressed). 

**Describe alternatives you've considered**
Sticking with system.io.

**Additional context**

**Comment by natemcmaster** [comment]
I don't think it's currently possible to do this. APIs this library calls in System.Runtime.Loader.AssemblyLoadContext requires file paths. Introducing a file provider abstraction means I would also need to know whether or not the file provider is physical or not....which IMO defeats the purpose of the abstraction.

**Comment by dazinator** [comment]
Could the load from stream method be used instead to load the assembly? 

https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromstream?view=netcore-2.2#System_Runtime_Loader_AssemblyLoadContext_LoadFromStream_System_IO_Stream_

I know this wouldn't cater for unmanaged / native libs.

Perhaps another option.. When the ALL can't find an assembly at an expected path, I think it raises a resolve event to allow you to satisfy the resolution manually - perhaps here would be a good place to query from an IFileProvider?

**Comment by natemcmaster** [comment]
LoadFromStream might work, but LoadFromPath is optimized to handle on-disk assemblies better. LoadFromStream requires paging the entire assembly into memory.

And like you mentioned, this is only available for managed assemblies.

**Comment by dazinator** [comment]
ah ok.

Perhaps a better way forward for me then,  is first shadow-copy the plugins from the IFileProvider to some temp physical directory first on startup, and then use dotnetcoreplugins to load them from there as normal. I can then IFileProvider.Watch for changes to plugins in the source at runtime and when they change, Unload the ALC, shadow copy again the new versions, and reload them with dotnetcoreplugins again. Should allow me to host plugins anywhere IFileProvider supports. Should also allow me to update the plugins at the source because they won't be locked by any process due to the addition of the shadow copy before load. I'll close this

**Comment by natemcmaster** [comment]
Yeah, that sounds like a better approach.
