### ISSUE TITLE
Any plans to integrate this officially in .NET Core/ASP.NET Core?

### ISSUE THREAD

**Issue by NiklasTeich** [natemcmaster/DotNetCorePlugins#36]
Hi Nate!

Very interesting project - any plans to integrate this kind of plugin system directly in .NET Core/ASP.NET Core? I think it would be extremly awesome to have it "natively" on board!

Greetings!
Niklas

**Comment by natemcmaster** [comment]
The .NET Core team has seen my project, but currently does not plans to make this officially part of .NET Core.
