### ISSUE TITLE
Hot reloading plugins in .NET Core 3 on run-time (without restarting the app)

### ISSUE THREAD

**Issue by HamedFathi** [natemcmaster/DotNetCorePlugins#37]
**Is your feature request related to a problem? Please describe.**
More than a year ago I wrote a library for loading plugins. To prevent plugins from being inaccessible by the system, I loaded all the plugins directories in memory. I was monitoring the directory changes (PhysicalFileProvider Watch()), and whenever the plugin was added, I loaded it automatically.

You can find it [here](https://github.com/HamedFathi/LoadEngine/blob/master/LoadEngine/LoadEngine.cs)

Is it possible to do like this with your plugin system? Replace an assembly (plugin) and reload it automatically? (even publish a message to subscribers to update\refresh the UI and ...!)

**Describe the solution you'd like**
Unfortunately, I am not familiar with the new way on .NET Core 3 so I asked you about hot reloading the plugins!

**Additional context**
In my solution, we can copy/paste any plugin on plugin directory and LoadEngine and reload it instantly and automatically it helps us to have a very dynamic plugin system without restarting the web servers or applications.
I hope it is possible in .NET Core 3 and your awesome plugin system.

**Comment by natemcmaster** [comment]
This is not yet supported. It should be possible to implement unloading of assemblies now that #31 has been implemented, but this is not something I plan to implement myself. The tricky part in making hot reloading work well will to be sure that unload actually happens.

I'll put this in the backlog and label as 'help wanted'. If you are interested in implementing hot reloading, let me know.

**Comment by HamedFathi** [comment]
@natemcmaster 

In fact, I loaded all the information into the memory (as a stream) with my library for this goal but here I expect to be able to free the plugin`s file by calling ```Dispose```'s function in ```.NET Core 3.0```.
This implementation is exactly the same as your sample.

```cs
var loaders = new List<PluginLoader>();

// create plugin loaders
var pluginsDir = Path.Combine(AppContext.BaseDirectory, "plugins");
foreach (var dir in Directory.GetDirectories(pluginsDir))
{
    var dirName = Path.GetFileName(dir);
    var pluginDll = Path.Combine(dir, dirName + ".dll");
    if (File.Exists(pluginDll))
    {
        var loader = PluginLoader.CreateFromAssemblyFile(
         pluginDll,
         isUnloadable: true, // <<<<<<<<<< HERE
         sharedTypes: new[] {
                typeof(IPlugin)
         });
        loaders.Add(loader);
    }
}

// Create an instance of plugin types
foreach (var loader in loaders)
{
    foreach (var pluginType in loader
     .LoadDefaultAssembly()
     .GetTypes()
     .Where(t => typeof(IPlugin).IsAssignableFrom(t) && !t.IsAbstract))
    {
        // This assumes the implementation of IPlugin has a parameterless constructor
        IPlugin plugin = (IPlugin)Activator.CreateInstance(pluginType);

        Console.WriteLine($ "Created plugin instance '{plugin.GetName()}'.");
    }
    loader.Dispose(); // <<<<<<<<<< HERE
}

Console.ReadKey();
```

![Screenshot_1](https://user-images.githubusercontent.com/8418700/55856349-45b56200-5b7f-11e9-9901-3b560f919278.png)

How can I do this step first?

**Comment by natemcmaster** [comment]
See https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability-howto. This is what I meant by unloading would be tricky. Unload can’t happen until GC has cleaned up all memory used by your plugin. GC collection runs asynchronously.

**Comment by natemcmaster** [comment]
Another request for this feature: https://github.com/natemcmaster/DotNetCorePlugins/issues/48

**Comment by natemcmaster** [comment]
I would like to understand the use cases for hot reloading better. Can anyone share more about how they would like to use this feature? I personally have never tried to do this in .NET Core as `dotnet watch` fulfills my needs. That said, I'm not opposed to adding this.

What do you think about an API that looks like this?
```c#
var loader = PluginLoader.CreateFromAssemblyFile(pathToDll, config => config.EnableHotReload = true);
loader.OnPluginLoaded += MyReloadHandler;
loader.OnPluginUnloaded += MyUnloadHandler;

void MyReloadHandler(object sender, PluginLoadedEventArgs eventArgs)
{
  doSomething();
}
void MyUnloadHandler(object sender, PluginUnloadedEventArgs eventArgs)
{
  doSomethingElse();
}
```

If the primary scenario is to use with ASP.NET Core, I would also be okay using Microsoft.Extensions.Primitives.IChangeToken instead of events (see https://docs.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens). I'm less certain of this API because (again) I'm not sure how users intend to use hot reloading.

```c#
var loader = PluginLoader.CreateFromAssemblyFile(pathToDll, config => config.EnableHotReload = true);
IChangeToken reloadToken = loader.GetReloadToken();

// pass reload token to something else.
```

Thoughts?
cc @AdrianoAE @HamedFathi @zHaytam

**Comment by zHaytam** [comment]
Hi!
Personally, I'm working on a personal project which is an extensible blogging platform.
The idea is to be able to add/remove plugins almost like Wordpress. Each plugin adding some kind of functionality:

- Some of the functionalities are gonna be related to views/controllers, which means I'll need to add these on the go. (Ps: I still didn't find how would I be able to add/remove controllers/views past startup).
- Some other functionalities will be unrelated to ASP.NET Core, such as custom filters, changing how a certain functionality works (e.g. sending emails) and some other things.

As I said, for the ASP.NET Core related things I still didn't figure out how to unload things at runetime (even if a Hot Reloading feature is available).
For the other things, I was thinking of using your plugin, encapsulate each plugin with a `WeakReference` and when unloading, wait until `IsAlive` is false which then removes all added functionality from that plugin.

About the API you suggested, that would work for my second scenario! I was also thinking about using events to know when an plugin is loaded/unloaded.

For the `IChangeToken` you mentionned, I have never heard of it and thus I'll need to do some researching to better understand how it works :')

**Comment by HamedFathi** [comment]
Hi @natemcmaster 

Long-time ago I did this, You can find the source code [here](https://github.com/HamedFathi/LoadEngine)

Let's talk about a scenario

I developed an application and deployed it. Each part of my application (ASP.NET Core) is a plugin.
Now I want to update one of them (plugins) The first terrifying thing to come to mind is Should I reset my server? or Can I replace my `DLL` (plugin) without restarting (Hot reloading) and see the result right after that or after the first login.

I would be great if we replace plugins (DLLs) without restarting the application and get feedback from them. (with callback, event or even SignalR)

As you mentioned before in your blog 

> Unloading - once a plugin is loaded, the files it uses are locked by the process. The only way to unload a plugin is by killing the host app.

So the concept of `Hot reloading` was meaningless at least before .NET Core 3.

I implemented this feature by loading the whole assembly (All assemblies in a folder) in memory. 
However, this method does not look good because it is very difficult to manage dependencies.
I have to reload all the contents in the folder with each change in a plugin/DLL.

In my implementation I had two events:
```cs
   public event ChangedDelegate OnChange; // For each changes
   public event ChangedDelegate OnLoad; // First time
```

I used `IFileProvider` to watch files changes.

```cs
private async Task WatcherAsync()
        {
            var pattern = (_ctx.SearchOption == System.IO.SearchOption.TopDirectoryOnly ? "" : "**/") + _ctx.Filter;
            IChangeToken token = _fileProvider.Watch(pattern);
            var tcs = new TaskCompletionSource<object>();
            token.RegisterChangeCallback(state =>
                ((TaskCompletionSource<object>)state).TrySetResult(null), tcs);
            await tcs.Task.ConfigureAwait(false);
            UpdateAssemblies();
        }
```

After all of these, I used `LoadEngine` as an extension method for All famous IOCs.

**Startup.cs**
```cs
service.RegisterLoadEngine<IPlugin>(/*...*/) 
```

I think the API you mentioned above is quite appropriate and in some ways similar to my approach. I never expanded the `LoadEngine` because your library is more complete.

I hope you add this feature as well.

**Comment by AdrianoAE** [comment]
Hello,

At work I got asked to work on a plugin system that could be used to load/reload plugins at runtime without shutting down the application. The requirements were:
• Each plugin has to implement all the logic it requires to work;
• Managed by a "Master" class that would say what are the functionalities they have to implement;
• The plugins configuration should be editable in a Backoffice throught a database, and based on them the plugins should be loaded/unloaded (the logic is managed by the Master Class);
• We need to be able to add and update the plugins at runtime without shutting down the apps.

The first aproach is easier to understand, will take a look at IChangeToken to see how it works (never seen it before). 

Regards.

**Comment by natemcmaster** [comment]
I think the first and last requirements you listed are germane, but the others outside the scope of what I'd like to support with this library.

I'm currently favoring an event API instead of a change token. Integrating dynamic reloading with ASP.NET Core is a whole new can of worms I'm not ready to open yet.

**Comment by jzabroski** [comment]
> Can anyone share more about how they would like to use this feature?

Hot reloading is used a lot in the Java world to minimize downtime.  Savvy architects might counter with, "Dude, just use a server farm and stagger your app pool recycling."  However, what if you need really tight timeline for when you reload?  (I think this is a mighty big IF, but consider a workflow scheduler like we had at erecruit - we built our own virtual machine on top of a Lisp-like dialect because we did not have native .NET hooks to suspend and resume a computation at well-defined suspension points. - You can't just suspend an EF query and then resume the computation consuming it and expect a lazy load operation to succeed.)

In an IDEAL world, in my opinion, you would have some way to "cut over" requests at a fixed time or event.  In Smalltalk, this "cut over" is event-driven based on messages sent to old objects with Tombstone markers.  However, I always thought, to minimize system drift bugs, the best solution is to have it work like a job scheduler.

Years ago, I debated Adam Chilpala on the ideal framework for routing web requests that was both secure and extensible.  Effectively, what I wanted was a lot like how Elastic Search handles indexes: you have a main route that defaults to the active index, but the non-active indexes don't go away until all active requests on those indexes expire/terminate.

**Comment by natemcmaster** [comment]
@jzabroski so, you are using plugins with a web server, and want to hot reload in production to avoid shutting down the web server when you want to deploy an updated version of your code?

**Comment by jzabroski** [comment]
Yeah, that sums up everything.

**Comment by natemcmaster** [comment]
Ok, @everyone on this issue, I've implemented a simple version of hot reloading. I'd like your input before I merge. Bonus points if you can clone the branch, build it, and give it a try yourself:

https://github.com/natemcmaster/DotNetCorePlugins/pull/62

**Comment by jzabroski** [comment]
In the words of [Egyptian Sun God Ra](https://www.reddit.com/r/nyjets/comments/ba5sf0/robby_anderson_is_actually_the_egyptian_sun_god_ra/), I like bonus points.

**Comment by jzabroski** [comment]
Why does the HotReloadApp require netcoreapp3.0?

@natemcmaster It's a shame someone has already taken the GitHub handle YoungAmazing, because it would be perfect for you.

**Comment by zHaytam** [comment]
Because the ability to "unload" assemblies is only possible in .net core 3

**Comment by jzabroski** [comment]
@zHaytam I did not connect the dots at 7am before my IV drip of caffeine was complete.  Thank you.

@natemcmaster  The Strawberry and Banana isn't stale, but you missed an obv. [opportunity to freeze a banana and hammer with it ](https://www.youtube.com/watch?time_continue=109&v=sGkK0Bk7KJ4)in a hot reload.

**Comment by przemo098** [comment]
Is there any progress ?

**Comment by jzabroski** [comment]
@przemo098  This is done - not sure what you are asking?
