### ISSUE TITLE
System.InvalidCastException when trying to create instance of loaded plugin type

### ISSUE THREAD

**Issue by LaterStart** [natemcmaster/DotNetCorePlugins#42]
Hi,
I'm experiencing problems when trying to activate instance of plugin type that inherits interface type.

For example I have "Context" type that implements "IContext" interface which I am trying to load using PluginLoader.

**Here is the part where the type is loaded:**
```c#
        private static Type GetContextType()
        {          
            var pluginPath = Path.GetFullPath(Const.PersistencePath);
            var loader = PluginLoader.CreateFromAssemblyFile(pluginPath);
            var assembly = loader.LoadDefaultAssembly();
            var types = assembly.GetExportedTypes();
            var type = types.Single(t => t.Name == "Context");

            return type;
        }
```

**And here is the part where the exception occurs:**
`public static IContext LoadContext(string connectionString) => (IContext)Activator.CreateInstance(GetContextType(), connectionString);`

`System.InvalidCastException: 'Unable to cast object of type 'Vigab.Persistence.Context' to type 'Vigab.Application.Interfaces.IContext'.'`

**Context class:**
```c#
public sealed class Context : DbContext, IContext
{        
        public Context(string connectionString) : base(new DbContextOptionsBuilder()
            .UseSqlServer(connectionString)
            .Options) { }
}
```

**Additional info:**
Presentation layer references application layer which only has interface IContext.
Persistence layer is the plugin which implements IContext interface and should be loaded dynamically without having references included into presentation or application layer. It also depends on Entity framework and System.Data.SqlClient, which seems to be unmanaged assembly, because of which I have tried to use this library as probable solution.

**Comment by natemcmaster** [comment]
Try changing your code to this:
```c#
 PluginLoader.CreateFromAssemblyFile(pluginPath, sharedTypes: new [] { typeof(IContext) });
```
By default, PluginLoader loads plugins in isolation from each other. You have to opt-in to sharing types across the boundary of the plugin and the host app.

**Comment by LaterStart** [comment]
This solved the issue, thanks. But in order to pass type loading I had to add three more shared types.
`typeof(DbSet<Test>), typeof(Test), typeof(IRequest). `

**Now exception occurs on Context constructor.**
`System.TypeLoadException: 'Method 'ApplyServices' in type 'Microsoft.EntityFrameworkCore.SqlServer.Infrastructure.Internal.SqlServerOptionsExtension' from assembly 'Microsoft.EntityFrameworkCore.SqlServer, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.'`

It seems like it isn't loading plugin dependencies properly?

**Comment by natemcmaster** [comment]
Try adding `typeof(SqlServerOptionsExtension)` too.

Or, since it appears you want to unify many assemblies, consider using this overload instead. This means "sharedTypes = all, if possible"
```csharp
 PluginLoader.CreateFromAssemblyFile(pluginPath, PluginLoaderOptions.PreferSharedTypes);
``

**Comment by LaterStart** [comment]
Thank you, it works perfectly! :)
