### ISSUE TITLE
Allow building compile dependencies for the plugin loader (optionally)

### ISSUE THREAD

**Issue by gasparnagy** [natemcmaster/DotNetCorePlugins#46]
**Is your feature request related to a problem? Please describe.**

When using the plugin loader for testing tools, it might be required to load the (ASP.NET Core) compile time dependencies as well. (In my case it was missing `Microsoft.AspNetCore.Hosting.Abstractions`, see https://github.com/specsolutions/deveroom-visualstudio/issues/5.)

**Describe the solution you'd like**

I have made a solution based on v0.2.4, that allows to control this behavior through `PluginLoaderOptions` and add the necessary libs in the AddDependencyContext.

The code can be found in this commit: https://github.com/gasparnagy/DotNetCorePlugins/commit/b03be18f048720912dbb893a498ef83e3a62bdb0
It is currently not applicable to `master` because the plugin loading conf has been changed since then. Any suggestion is welcome, how this could be applied to the master and I will send a PR.

**Describe alternatives you've considered**

I could not figure out any other.

**Additional context**

Please note that #45 is required for this to work.

**Comment by gasparnagy** [comment]
Probably it is related to #19

**Comment by natemcmaster** [comment]
I don't think I would add this to the AssemblyLoadContext itself. Compile libraries are only meant to be used by the compiler, not by the runtime. In many cases, compile libraries _are_ runtime libs, but this is not always true. In cases when a compile library is not a runtime lib, you would get runtime errors, or the load might fail completely. (For example, [reference assemblies for Microsoft.Extensions 3.0 and up](https://github.com/aspnet/Extensions/blob/cd354ff78d628f8762db9efa7f1003ce512fce7f/src/Shared/src/ReferenceAssemblyInfo.cs#L4-L9) )

What do you need the compilation library for?

**Comment by gasparnagy** [comment]
You are generally right. (And thx for the great project btw.) Theoretically this should not be needed. It looks like though, that ASP.NET Core puts some hosting-related components into the compile dependencies only, so without them the library is not able to load the assembly. Maybe there is a better solution, but I could not figure out any. (BTW, I am filtering out the compile dependencies and only add the ones that are actual runtime libraries -- with this solution it works pretty well.)

I will try to prepare a small repro that shows the particular problem. Maybe you can suggest a better solution based on that.
