### ISSUE TITLE
Unrelated question

### ISSUE THREAD

**Issue by dferretti-fig** [natemcmaster/DotNetCorePlugins#47]
I've got a question for you unrelated to this repo (sorry!) but about something I think you mentioned some time ago. It was in some other dotnet or aspnet repo middle to late of last year and I can't seem to find it, otherwise I would just respond there. And if I'm misremembering or way off base here then feel free to delete hah.

Whichever project it was, was just beginning to move to the Arcade system, and you (I think it was you) were expressing uneasiness about having to keep these generated and automatically managed files, specifically related to the build process, inside the git repo. I am starting to feel the same apprehension at my work - has there been any discussion or changes to this?

Specifically, I'm looking to automate generating the pipeline yaml as part of the build process itself. For example, I have a dotnet solution with X projects in it which each require a set of build phases and steps. Right now I can run a tool locally that will generate the correct yaml pipeline, but then it must save it to the repo before it can run in AzDO. Even with putting as much as possible into remote yaml template git repositories, I still need that entrypoint yaml to call out to that template X times, and this file must be regenerated each time more projects are added to the solution. 

I'd like to be able to have an HTTP endpoint as a remote template source rather than a git repo - so that endpoint could analyze the solution and respond with a dynamic yaml template with the desired number of phases. 
Or maybe the build pipeline only contains one phase, but that single phase performs the analysis (or reaches out to a separate system that manages our pipelines) and adds more phases to the currently running build somehow. 

I'm asking you because from what I recall (or maybe I've made this whole memory up) you were trying to suggest something similar for darc/maestro. Was that a battle that was lost? Or is there something in the works along those lines? Is there anywhere more appropriate I can ask this? I've tried over at azure-pipelines-yaml but haven't found anything just yet.

Thanks!

**Comment by natemcmaster** [comment]
Hey David, there are a few pieces to your questions. I'm also going to send you an email with a few more details.

For anyone else seeing this, Maestro/Arcade are part of the .NET Team's build system. Use https://github.com/dotnet/arcade if you have issues using it on your own. YAML pipelines are part of Azure DevOps, so I would recommend using https://developercommunity.visualstudio.com/content/problem/post.html?space=21 to send feedback to the Azure DevOps team.

-Nate
