### ISSUE TITLE
Plugins with satellite assemblies

### ISSUE THREAD

**Issue by nguerrera** [natemcmaster/DotNetCorePlugins#5]
One issue that has hit both msbuild and roslyn with AssemblyLoadContext is that they're custom loaders did not find satellite assemblies.

https://github.com/dotnet/roslyn/issues/29014
https://github.com/Microsoft/msbuild/issues/2203

Is that handled automatically by this project?

**Comment by natemcmaster** [comment]
It's one of the known issues I haven't addressed yet. It's one I definitely want to fix.

**Comment by nguerrera** [comment]
Nice. :)
