### ISSUE TITLE
Resolve native assemblies from NuGet package

### ISSUE THREAD

**Issue by rozele** [natemcmaster/DotNetCorePlugins#53]
**Is your feature request related to a problem? Please describe.**
I have a plugin with a dependency on Microsoft.CognitiveServices.Speech, which has native dependencies in the runtimes folder that are resolved per platform. When the P/Invoke call occurs from inside Microsoft.CognitiveServices.Speech after resolving the plugin with `PluginLoader.CreateFromAssemblyFile`, I get a `DllNotFoundException`.

**Describe the solution you'd like**
I'd like the `PluginLoader` to also search the runtimes folder in the base path for the `AssemblyLoadContext` so that I do not get the `DllNotFoundException` for the native dependency.

**Describe alternatives you've considered**
Haven't started thinking about alternatives.

**Additional context**
No additional context.

**Comment by natemcmaster** [comment]
This is a supported scenario, in fact, there are tests for this. Can you share steps to reproduce this error? What do your project files look like?

**Comment by rozele** [comment]
I'll send you a repro today.

**Comment by rozele** [comment]
Run the main Console app (PluginLoaderTest) on macOS from:
https://github.com/rozele/PluginLoaderTest

**Comment by rozele** [comment]
(Haven't tested on Windows yet)

**Comment by rozele** [comment]
FYI - I get the same exception for `dlopen` when I use the latest NuGet preview package (and I also noticed that the `sharedTypes` feature is not working as expected there. I.e., I changed to:
```
            var assembly = PluginLoader.CreateFromAssemblyFile(
                    assemblyFile,
                    sharedTypes: new[] { typeof(ITest) })
                .LoadDefaultAssembly();
```
And when I run:
```
        var test = new ContainerConfiguration()
                .WithAssembly(assembly)
                .CreateContainer()
                .GetExport<ITest>();
```
I am not able to resolve an `ITest` from that assembly with `System.Composition`.

**Comment by rozele** [comment]
Here's the exception for quick reference:

**System.DllNotFoundException**
Unable to load shared library 'Microsoft.CognitiveServices.Speech.core.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMicrosoft.CognitiveServices.Speech.core.dll, 1): image not found

**Comment by natemcmaster** [comment]
I see the problem. Make this change to your TestPlugin.csproj file:
```diff
 <Project Sdk="Microsoft.NET.Sdk">
 
   <PropertyGroup>
-    <TargetFramework>netstandard2.0</TargetFramework>
+    <TargetFramework>netcoreapp2.1</TargetFramework>
   </PropertyGroup>
 
   <ItemGroup>
```

**Explanation**

.NET Standard 2.0 is a platform-less, runtime-agnostic API surface. When your project compiles a plugin for .NET Standard 2.0, all native assemblies are excluded from build output and the dependencies metadata. This is by-design. I opened a bug about this years ago against the .NET SDK team to request changes that would have fixed your exact scenario, but there is no plan to make this work. See https://github.com/dotnet/core-setup/issues/635 and this comment https://github.com/dotnet/core-setup/issues/635#issuecomment-284516681

I can't think of anything this library can do to workaround it...except maybe make the documentation clearer. Thoughts?

**Comment by rozele** [comment]
Okay - so this library uses a .NET Core API to load the native dependencies? It's strange that it works as expected if take a direct package dependency (meaning .NET Core has some mechanism to resolve the dependency from .NET Standard). Is it possible to add a configuration to tell the PluginLoader to look for .NET Standard libraries?

Otherwise, for now, I can just change the target framework.

**Comment by natemcmaster** [comment]
The reason it works as a direct package dependency is the same reason changing target frameworks works. The mechanism by which this is happening is the .deps.json file. The .NET Core SDK resolves native assemblies at _build time_ for netcoreapp2.1 and puts a list of the .dylib/.dll/.so files into the .deps.json file. The SDK doesn't include this in the .deps.json file for a .NET Standard project. My library reads the .deps.json file to determine which dependencies should be loaded, so I can't really think of a why my library can solve this problem.

**Comment by rozele** [comment]
@natemcmaster Unrelated question - I got things working when running from VS, but I'm working on a .NET Core CLI tool extension so I pack the output before running it. When I use the <PluginProject> and <Target /> approach to build the project, the plugin folders are not included in the NuGet output. Have you used this approach for a NuGet package, and is there a quick way (without setting up a .nuspec file) to ensure the plugin libraries are included in the .nupkg?

**Comment by rozele** [comment]
Thanks! This works.

**Comment by rozele** [comment]
Hey @natemcmaster - quick question. When I switch to using:
```
  <Target Name="BuildPlugin" BeforeTargets="Build">
    <MSBuild Projects="..\MyPlugin\MyPlugin.csproj" Targets="Publish" Properties="Configuration=$(Configuration);PublishDir=$(OutputPath)/plugins/MyPlugin/" />
  </Target>
```
And try to create a NuGet package for the "host" project as a .NET Core CLI tool, the `plugins` folder is not included in the .nupkg. I can setup a .nuspec file to get the `plugins` folder, but I was wondering if you had any tips / ran into this issue and figured out how to inform MSBuild to include the `plugins` folder without creating a .nuspec.

**Comment by natemcmaster** [comment]
> as a .NET Core CLI tool

Are you using `<PackAsTool>true</PackAsTool>`?

**Comment by rozele** [comment]
Yup.

**Comment by natemcmaster** [comment]
> I can setup a .nuspec file to get the plugins folder, but I was wondering if you had any tips / ran into this issue and figured out how to inform MSBuild to include the plugins folder without creating a .nuspec.

Disclaimer first....if you're not familiar with MSBuild targets, properties, and item groups, it's probably better to use a nuspec file. I usually recommend nuspec for complex packing tasks because I think the "API" for customizing a package via csproj is awful.

Nuspec generation in csproj relies on MSBuild items to tell it what to pack. There are a few magic default settings which pick up build outputs for most simple class libraries and console tools. But the magic falls apart when you need to include generated content (such as a plugins folder). You can write your own magic by adding files to the `TfmSpecificPackageFile` item group as a part of a target that is listed in the `TargetsForTfmSpecificContentInPackage` property. I haven't tested this on my own, but I imagine the result would look something like this:

```xml
<PropertyGroup>
  <TargetsForTfmSpecificContentInPackage>BuildPlugin;$(TargetsForTfmSpecificContentInPackage)</TargetsForTfmSpecificContentInPackage>
</PropertyGroup>
 
<Target Name="BuildPlugin" BeforeTargets="CoreBuild">
  <PropertyGroup>
    <MyPluginOutputPath>$(OutputPath)/plugins/MyPlugin/</MyPluginOutputPath>
  </PropertyGroup>

  <MSBuild 
    Projects="..\MyPlugin\MyPlugin.csproj"
    Targets="Publish" 
    Properties="Configuration=$(Configuration);PublishDir=$(MyPluginOutputPath)" />

  <ItemGroup>
    <TfmSpecificPackageFile Include="$(MyPluginOutputPath)**/*">
      <PackagePath>tools/$(TargetFramework)/any/plugins/MyPlugin/</PackagePath>
    </TfmSpecificPackageFile>
  </ItemGroup>

</Target>
```

By the way, checkout https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.PackTool.targets and https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets to see what the SDK is doing under the hood.

**Comment by rozele** [comment]
Thanks @natemcmaster - the \<TargetsForTfmSpecificContentInPackage\> did the trick
