### ISSUE TITLE
.deps.json as Intermediary format for assembly loading

### ISSUE THREAD

**Issue by jzabroski** [natemcmaster/DotNetCorePlugins#61]
@natemcmaster  Here is draft number one of my proposal based on discussion in #41 - I think it needs a bit more refining (fewer words, clearer user stories), but let me know your thoughts.  I also think this might be two "RFCs" in one at the moment, so we may want to break this issue into two in the future:
1. analysis of dependencies
2. run-time construction of dependencies.

**Is your feature request related to a problem? Please describe.**
- As a developer, I want to load assemblies from my executable's .deps.json file, so that I have a well-defined manifest for what assemblies can be loaded, as well as what transitive dependencies are required to be loaded.
- As a developer, I want to create additional .deps.json files that mirror DotNetCorePlugins contexts, so that I have a human readable data structure similar to the old bindingRedirect xml syntax.

**Describe the solution you'd like**
1. Human readable (e.g., json or xml) data structure that defines, per plugin:
    - Where to locate assemblies
    - What acceptable assembly versions
    - Transitive dependencies required by the plugin
    - 32-bit/64-bit/AnyCPU scenario handling
2. Bonus if that data structure matches exactly the .deps.json format used by the CLR to load an executable's dependencies, accessible via: `System.AppContext.GetData("APP_CONTEXT_DEPS_FILES")`
3. Bonus if solution can expose nicer API than `System.AppContext.GetData("APP_CONTEXT_DEPS_FILES")`
4. Bonus if there is a command line tool to generate a `.deps.json` file for a given DLL.
    - This is effectively feature parity with Java's Maven tool and it's [`dependency:analyze` plugin goal](https://maven.apache.org/plugins/maven-dependency-plugin/analyze-mojo.html)
    - Think of this as a tool that performs analysis of possible `AssemblyLoadContext` "participants".  This would work similar to ReSharper's "Did you forget to include a reference to this assembly?" tooltip suggestion in Visual Studio, except for v1, it is probably best to make it a batch-mode .NET CLI Tool.
    - Bonus would be to have a `test-run` command which would validate, using Roslyn, that all transitive dependencies can be loaded.

**Describe alternatives you've considered**
Use Microsoft.DotNet.PlatformAbstractions package or Microsoft.Extensions.FileSystemGlobbing to round up all *.dll files matching a certain prefix. The problem with this approach is it doesn't specify sequential ordering requirements for loading dll's.

**Additional context**
Seems similar to request #11 which was closed due to inactivity.  Except my request has a bit more "meat on the bone".

**Comment by natemcmaster** [comment]
Thanks for writing this up. The scope of this is pretty large, and I'm not sure exactly where to go with it because the way I see it, most of this is already solved. Here are some things already implemented:

* `PluginLoader` already uses the `.deps.json` file (if present) at runtime to prepopulate a list of assemblies that can be loaded. This file is read automatically if it is present next to your plugin executable on disk...which it typically is.
* `PluginLoader` allows you to load any of the assemblies in a plugin, not just the 'entry point' assembly, by calling `loader.LoadAssembly(assemblyName)`
* `dotnet build` is the "command line tool to generate the .deps.json file". It produces the well-known format when you compile a .csproj. The file is (obviously) compatible with the CLR, and it includes:
  * a list of of assembly versions
  * the complete transitive closure of dependencies
  * the ability to differentiate on CPU architecture
  * hints about where to find assemblies (in the form of short relative paths describing the location inside the NuGet cache or a runtime store)

Can you clarify what's missing?

**Comment by jzabroski** [comment]
I am almost wrapping up an awful project where I had to decompile lost source code and restore it to the best of my ability.  I have NOT forgotten about your question.

**Comment by jzabroski** [comment]
I wrapped up my awful project yesterday.  I am going to try to up-priority this and the xunit-extensions stuff.

**Comment by jzabroski** [comment]
I think there is a problem with my proposal, before I elaborate what I meant.

Short and sweet: C# supports referring to two different types with the same name via _extern aliases_, but .deps.json does not support this feature.
Here is the related issue: https://github.com/NuGet/Home/issues/4989

Based on this, I think it is not worth the time to pursue this project at this time.


Background Noise:
Years ago, I had written a rant to Rob Relyea via The Silverlight Forums about similar flaws in XAML specification, whereby XAML did not support extern aliases, leading to the inability to load two different versions of the same assembly. My use case was a Composite application with two different versions of a datagrid from the same datagrid manufacturer: The earlier DataGrid 'leaked' implementation details on how row detail templates were handled, causing a breaking change when those implementation details were made private in a later version.

I guess this just goes to show you that people think of dependencies in a very literal way, and do not consider Dependency Diamonds at all.  We've been stuck with these problems since Registry Hell first existed.  I can name names upon names of failures here: e.g., Tim Ewald and Don Box brought us Microsoft COM+ bag of hell.

 I wonder what SalesForce does to avoid these problems with SalesForce apps.  My hunch is they use a strict form of Application Shell Architectural Style I mentioned in #60 .

**Comment by natemcmaster** [comment]
Ok. Closing as I'm not planning on any action items.
