### ISSUE TITLE
Antiforgery token validation failed - Form post

### ISSUE THREAD

**Issue by naviti** [natemcmaster/DotNetCorePlugins#77]
I am using your library similar to your sample "aspnetcore-mvc" but with Razor Pages. This works beautifully until I set up a simple from like this:

```
<form method="post">
    <button type="submit">Save</button>
   … some other unrelated fields..
</form>
```

If I hit the button then the request does not work. Because it is intercepted from the .net core framework with the following message:

> Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter: Information: Antiforgery token validation failed. The required antiforgery cookie ".AspNetCore.Antiforgery.Fda_KFWU8eY" is not present.

> Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The required antiforgery cookie ".AspNetCore.Antiforgery.Fda_KFWU8eY" is not present.
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.ValidateRequestAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.ValidateAntiforgeryTokenAuthorizationFilter.OnAuthorizationAsync(AuthorizationFilterContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.AutoValidateAntiforgeryTokenAuthorizationFilter'.
Microsoft.AspNetCore.Mvc.StatusCodeResult: Information: Executing HttpStatusCodeResult, setting HTTP status code 400
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker: Information: Executed page /Plugin in 106.3939ms

Well, as you know Razor Pages are designed to be automatically protected from cross-site request forgery (CSRF/XSRF) attacks. Anti-forgery token generation and validation is automatically included in Razor Pages.

I can get this to work by disabling this security feature like shown below, but this would be bad practice...
`.AddRazorPagesOptions(o =>
                {
                    o.Conventions.ConfigureFilter(new IgnoreAntiforgeryTokenAttribute());
                })`

How could I use your library without having to disable the Antiforgery feature?

Thank you very much for your help!

**Comment by natemcmaster** [comment]
Can you send steps to reproduce this? I added a simple form to my aspnetcore-mvc sample and antiforgery worked perfectly, so not sure what's not working for you.

**Comment by naviti** [comment]
Guten Tag

Am 10.10.2019 bin ich wieder am Arbeitsplatz erreichbar.

In ganz dringenden Fällen können Sie mich auf dem Mobiltelefon erreichen: 079 443 96 03

Besten Dank und Gruss
Jonas Knaus

-------------------------------------
naviti GmbH
Jonas Knaus
Tulpenstrasse 350
5732 Zetzwil
Büro: 062 511 50 77
Mobile: 079 443 96 03
jonas.knaus@naviti.ch
www.naviti.ch
-------------------------------------

**Comment by naviti** [comment]
Hi Nate, thank you for your information.
I guess you need to add a Razor Page not MVC to see the problem.
I made a test project for you, please have a look at:
https://github.com/naviti/PluginTest

There you should see the problem.
thank you!

**Comment by natemcmaster** [comment]
I think you're missing the FormTagHelper. Try adding this to your .cshtml file

```razor
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
```

**Comment by naviti** [comment]
Hi Nate
Uhh..well..my fault! Thank you for the info about the FormTagHelper. It works perfectly after I added it to the project. Thank you very much for your help!
