### ISSUE TITLE
Re-loading the assembly re-creates the types

### ISSUE THREAD

**Issue by godrose** [natemcmaster/DotNetCorePlugins#79]
**Describe the bug**
Reloading the assembly creates a new set of types which are treated as different. This is different from the case where the framework loading is used.

**To Reproduce**
1. Using this version of the library '0.3.0'
2. Add breakpoint inside ``
2. Run tests for `SomeAssembly.Facade.IntegrationTests` project from
https://github.com/godrose/netcore-load/tree/master

**Expected behavior**
`MultipleLoadTests` is green
**Actual behavior**
`MultipleLoadTests` is red

**Additional context**
.NET Core 3.0, VS 2019, Test Explorer

**Comment by natemcmaster** [comment]
This is the intended behavior of creating multiple loaders or using the `.Reload()` method. If you want types to be the same, reuse the same instance of `PluginLoader` and don't call `.Reload()` on it.

**Comment by godrose** [comment]
@natemcmaster I don't think I invoke this method...

**Comment by natemcmaster** [comment]
> creating multiple loaders or using the .Reload() method

And what about the other one?

**Comment by godrose** [comment]
@natemcmaster I do create multiple loaders but here I'm just following the example. Maybe I got it all wrong...
```
//for each dll
var loader = PluginLoader.CreateFromAssemblyFile(
                    pluginDll,
                    sharedTypes: new [] { typeof(IPlugin) });
                loaders.Add(loader);
```

**Comment by natemcmaster** [comment]
Which example are you looking at? I can update samples and docs if they are unclear.

Otherwise, I don't think there is any action item here. It appears to me that PluginLoader is working the way it's intended, i.e. each instance of `PluginLoader` has a unique, isolated execution context.
