### ISSUE TITLE
get IMvcBuilder in plugin?

### ISSUE THREAD

**Issue by j4587698** [natemcmaster/DotNetCorePlugins#82]
I see the issues #13 , but it still adds controller in ConfigureServices. Is there any way to add controller from the plugin? I want to make a plugin system like Wordpress. When the plugin is enabled, I can automatically add my own page to the menu. 
Is there any way to solve this problem?

**Comment by natemcmaster** [comment]
This library doesn't support that, so you'd have to write code to so this yourself. If you figure out how to do it and want to contribute it as a feature of this library, let me know.

**Comment by SebastianStehle** [comment]
You just need an a plugin interface that provides you the IServiceCollection. You can then AddMvc multiple times.

In this method you can also register IStartupFilter: https://andrewlock.net/exploring-istartupfilter-in-asp-net-core/

**Comment by natemcmaster** [comment]
To be clear, I assumed @j4587698 was interested in adding controllers _after_ startup is done, but I was inferring that from his comparison to WordPress, which allows you to dynamically change plugins without rebooting the server process. This is what I was referring to when I said "this library doesn't support that".  

But if you're just talking about adding controllers from a plugin during startup, see https://github.com/natemcmaster/DotNetCorePlugins#support-for-mvc-and-razor. There is a simple API for that now.

**Comment by SebastianStehle** [comment]
Sorry, you are right.

**Comment by natemcmaster** [comment]
@j4587698 - does this API help with your request? https://github.com/natemcmaster/DotNetCorePlugins/pull/100

**Comment by j4587698** [comment]
@natemcmaster  Thank you for your reply

Unable to get imvcbuilder outside of configureservices.

I found https://stackoverflow.com/a/47629660.

I will try to register controllers
