### ISSUE TITLE
Load Views.dll

### ISSUE THREAD

**Issue by cpkuo** [natemcmaster/DotNetCorePlugins#83]
If my plugin is an aspnet core mvc project and it has a corresponding views.dll file but the main plugin dll doesn't explicitly reference the views.dll, is it possible to tell the plugin loader to also load the views.dll file so that when calling something like ICompositeViewEngine's GetView(null, "~/Views/Controller/MyViewName.cshtml", false), the corresponding views.dll can be searched?

**Comment by natemcmaster** [comment]
Yes, see the last section in https://github.com/natemcmaster/DotNetCorePlugins/blob/master/README.md

**Comment by cpkuo** [comment]
Thanks, by loading the plugin using this extension method, how can I retrieve the Assembly afterwards?

**Comment by cpkuo** [comment]
Ok great thanks! This works. I was able to just lookup the assembly in a separate routine after loading up all of the plugins using this extension method.

**Comment by natemcmaster** [comment]
Glad to hear it works!
