### ISSUE TITLE
More Events for Reloading

### ISSUE THREAD

**Issue by schmitch** [natemcmaster/DotNetCorePlugins#86]
Hello, I'm trying to build a Plugin System on top of your awesome Library.
I currently have the following use cases:
- Download & Start Plugins at runtime
- Upgrade Plugins at runtime
- Stop Plugins at runtime

while downloading, starting and stopping is actually working really nicely, reloading/upgrading has some caveheats.

currently I have uploaded a demo project at github here: https://github.com/schmitch/dotnet-plugin-demo

currently I need to have a Stop method called before reloading my plugin.
Unfortunatly I can only call it after the plugin got reloaded.

That is my log output:
```
Current Time V4: 23.10.2019 12:04:50
Reload Triggered, EventArgs: McMaster.NETCore.Plugins.PluginLoader / McMaster.NETCore.Plugins.PluginLoader
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
Created plugin instance 'Timestamp Plugin V5'.
Current Time V5: 23.10.2019 12:04:52
```

How it should be:
```
Current Time V4: 23.10.2019 12:04:50
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
Reload Triggered, EventArgs: McMaster.NETCore.Plugins.PluginLoader / McMaster.NETCore.Plugins.PluginLoader
Created plugin instance 'Timestamp Plugin V5'.
Current Time V5: 23.10.2019 12:04:52
```

Currently I think it would be possible by introducing an event that will be called, before `this._context.Unload();` is called. Maybe call it `BeforeReload` (i.e. `Reloaded` could also be deprecated in favor of `AfterReload`, then)?

**Comment by schmitch** [comment]
I also have the problem that I can't kill the application via. CTRL+C if I use a host-in-host (same repo, just the host-in-host) branch. It block forever.

**Comment by natemcmaster** [comment]
Why do you need need to call .Stop() before the assembly is reloaded? Can you elaborate more on what problem you're encountering?

> I also have the problem that I can't kill the application via. CTRL+C if I use a host-in-host (same repo, just the host-in-host) branch. 

Can you confirm that this problem is the result of DotNetCorePlugins? It seems to me like this problem would occur in a 'vanilla' project that isn't doing dynamic loading.

**Comment by schmitch** [comment]
> Why do you need need to call .Stop() before the assembly is reloaded? Can you elaborate more on what problem you're encountering?

Actually I need to call stop to correctly close everything in the plugin, like database connections.
Btw I created an example here: https://github.com/schmitch/dotnet-plugin-demo where I "create" a dotnet core host as a plugin, (i.e. the plugin could even start a web server that could be "hot" reloaded, but that means I need to stop it, before readding the new one)

> Can you confirm that this problem is the result of DotNetCorePlugins? It seems to me like this problem would occur in a 'vanilla' project that isn't doing dynamic loading.

nope this happens with `AssemblyLoadContext` aswell, it's just harder to debug with `DotNetCorePlugins`, because it's impossible to get **any** info about `Unloading`. (i.e. when using `AssemblyLoadContext` directly I can attach to the `Unloading` event and debug the issues. (It would be good if `DotNetCorePlugins` can give me the option to look into it aswell.)

Both things are just features, i.e. more events that either help by debugging and it helps to have a clean shutdown before the plugin gets unloaded.

**Comment by natemcmaster** [comment]
> Actually I need to call stop to correctly close everything in the plugin, like database connections.

Makes sense, but what problems are you having with the current API? The reason I'm asking is that I don't yet understand a compelling reason to add a new event API. An important thing to note about `AssemblyLoadContext.Unload()` is that it doesn't force unload and guaranteed that it will be unloaded; it just initiates the unloading. The unloading actually happens later, after garbage collection and threads and references are cleaned up. (See [docs](https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability) for more details.) Based on that, I suspect your use case still works, but if it's not, I'd like to know what kinds of issues you see (besides the log output not appearing in the order you expect).

**Comment by dazinator** [comment]
In terms of cleanup how about this:

1. As Reload is a public method, you could set up your own file watcher / event to call it, but before you do call Reload, do your "cleanup". This could take the form:

A) Make sure you call Dispose() on any disposable instances loaded from that assy load context. This is easier if for example you have a DI container responsible for the lifetime of all those types, and then you can just Dispose() that container.

**Comment by sgf** [comment]
> In terms of cleanup how about this:
> 
> 1. As Reload is a public method, you could set up your own file watcher / event to call it, but before you do call Reload, do your "cleanup". This could take the form:
> 
> A) Make sure you call Dispose() on any disposable instances loaded from that assy load context. This is easier if for example you have a DI container responsible for the lifetime of all those types, and then you can just Dispose() that container.

cant do that without download full source code.
because some thing is internal like ManagedLoadContext.

**Comment by sgf** [comment]
u are right,i do  own file watcher and call the Reload now. thanks for share your idea.

**Comment by sgf** [comment]
> 1. As Reload is a public method, you could set up your own file watcher / event to call it, but before you do call Reload, do your "cleanup". This could take the form:
> 

u are right,i do own file watcher and call the Reload now. thanks for share your idea.

**Comment by dazinator** [comment]
@sgf you are welcome, I do have some good ideas occasionally, not as often as I'd like ;-)

**Comment by natemcmaster** [comment]
FYI - this project is in maintenance mode right now. I updated the labels on this issue. See #117 for detail on what the applied labels indicate.
