### ISSUE TITLE
Load plugin From MemoryStream

### ISSUE THREAD

**Issue by dxramax** [natemcmaster/DotNetCorePlugins#91]
Is it possible to load plugin directly from memory stream and not DLL Assembly file ?

**Example** when using Roslyn to emit compiled code to `MemoryStream`, then use the `MemoryStream` to load the plugin directly instead of creating `Assembly` and save it to a file and then load it using `PluginLoader`.

**Use Cases**  useful in unit testing, I have source code which can be compiled to `MemoryStream` using Roslyn, load the plugin then change the source code and compile again, after that reload the plugin and test the changes without creating any files.

**Comment by natemcmaster** [comment]
This is not possible with the current API. New API would need to be added to the internal calss `ManagedLoadContext` support this scenario. It should be possible using https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext.loadfromstream?view=netcore-3.0.

Marking as 'help wanted'. This is something I'm okay adding if you want to write a pull request, but it doesn't seem like a very common scenario so I'll leave it up to you.

**Comment by dxramax** [comment]
Currently I will not have the time to write a pull request, thanks anyway.
