### ISSUE TITLE
An open call for contributors

### ISSUE THREAD

**Issue by natemcmaster** [natemcmaster/DotNetCorePlugins#94]
I am interested in having more contributors help me work on this project. There is room for improvement on this library, and I'm not planning to do it myself anytime soon. I don't have much time to work on open source anymore. I recently became a new father and also a new job which requires 2 hours of commuting. As you can imagine, I don't have much free time.  If you are interested in helping, please let me know.

Cheers,
Nate

**Comment by Andale-online** [comment]
Very interesting project, planning to include in mine. If you need help...

**Comment by natemcmaster** [comment]
@Andale-online - thanks for reaching out! To get started, could you look at the contributing guide I've proposed in https://github.com/natemcmaster/DotNetCorePlugins/pull/95? I'd like to know if these guidelines are helpful, uninviting, confusing, too long, or just right.

**Comment by Andale-online** [comment]
I think it's okay. Much shorter than most of the rule sets, maybe it needs some rules about topic and description style for issues, bugs etc

**Comment by natemcmaster** [comment]
Thanks for taking a look. I'm thinking I'll add a [code of conduct page](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project) as well.

By the way, I recently added [issue templates](https://github.com/natemcmaster/DotNetCorePlugins/tree/master/.github/ISSUE_TEMPLATE) to this project as an attempt to provide style guidance on issues and bug reports. I'm open to suggestions on these templates.

**Comment by jzabroski** [comment]
I'm always here to help ya, @natemcmaster dawg.

**Comment by Sewer56** [comment]
I use this library extensively in one project so I plan to stick around too.

Not 100% sure about what can be done to improve the library in the future, but I'll probably stick some cool stuff here and there in an occasional pull request.

**Comment by natemcmaster** [comment]
Thanks for your replies so far! I've written up my thoughts about where this project goes from here in https://github.com/natemcmaster/DotNetCorePlugins/issues/117.

Closing this as I think I got my point across - this project is open-source and open for contributions. If you'd like to help out, checkout these issues: https://github.com/natemcmaster/DotNetCorePlugins/labels/help%20wanted
